# Generated by Django 5.1 on 2026-09-26 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(db_index=True, max_length=32)),
                ('ref', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('ground_truth', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['use_case', 'id'], name='showcase_re_use_cas_b7313e_idx')],
                'constraints': [models.UniqueConstraint(fields=('use_case', 'ref'), name='uniq_uc_ref')],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('done', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('error', models.TextField(blank=True, default='')),
                ('decisions_per_second', models.FloatField(blank=True, null=True)),
                ('median_latency_ms', models.FloatField(blank=True, null=True)),
                ('agreement', models.JSONField(blank=True, default=dict)),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('profile', models.CharField(blank=True, default='', max_length=24)),
                ('device', models.CharField(blank=True, default='', max_length=16)),
                ('calibrated', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['use_case', '-id'], name='showcase_sh_use_cas_6f689c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('profile', models.CharField(blank=True, default='', max_length=24)),
                ('device', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='showcase.record')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='showcase.showcaserun')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['record', '-id'], name='showcase_de_record__908fa1_idx'), models.Index(fields=['run'], name='showcase_de_run_id_c0c7f0_idx')],
            },
        ),
    ]
