# Generated by Django 5.1 on 2026-09-26 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, unique=True)),
                ('use_case', models.CharField(db_index=True, max_length=32)),
                ('question_id', models.CharField(max_length=48)),
                ('question_type', models.CharField(blank=True, default='', max_length=16)),
                ('n_samples', models.PositiveIntegerField(default=0)),
                ('n_human', models.PositiveIntegerField(default=0)),
                ('bins', models.JSONField(blank=True, default=list)),
                ('bias', models.JSONField(blank=True, default=dict)),
                ('accuracy_raw', models.FloatField(blank=True, null=True)),
                ('accuracy_calibrated', models.FloatField(blank=True, null=True)),
                ('ece_raw', models.FloatField(blank=True, null=True)),
                ('ece_calibrated', models.FloatField(blank=True, null=True)),
                ('fitted', models.BooleanField(default=False)),
                ('fitted_at', models.DateTimeField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['scope'],
            },
        ),
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('created_by', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='showcaserun',
            name='policy_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showcaserun',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=48)),
                ('model_value', models.JSONField(blank=True, null=True)),
                ('model_confidence', models.FloatField(blank=True, null=True)),
                ('human_value', models.JSONField()),
                ('source', models.CharField(choices=[('manual', 'Human label'), ('ground_truth', 'Ground truth')], default='manual', max_length=16)),
                ('actor', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='showcase.record')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['record', 'question_id'], name='showcase_fe_record__58794d_idx')],
            },
        ),
    ]
