"""Spec-driven use-case packs (3/4): markets, insurance, health/life sciences, legal & compliance."""
from __future__ import annotations

PACKS_C: list[dict] = [
    # -----------------------------------------------------------------------
    # Finance / markets
    # -----------------------------------------------------------------------
    {
        "key": "market_news", "name": "Market news classification", "industry": "Finance",
        "monogram": "MW", "pattern": "map-reduce at scale", "prefix": "MKT",
        "blurb": "Classify every news item for direction and materiality before it touches a "
                 "portfolio system — the map-reduce-over-big-data pattern at wire speed.",
        "header": "News headline and first paragraph about a listed company",
        "primary": "text", "fields": [("ticker", "Ticker"), ("source", "Source")],
        "questions": {
            "direction": {"type": "choice", "instructions": "Direction of the news for the stock.",
                          "criteria": {
                              "positive": "The news is positive for the company's stock.",
                              "negative": "The news is negative for the company's stock.",
                              "neutral": "The news is neutral for the company's stock."}},
            "material": {"type": "boolean", "instructions": "Is the news material?",
                         "criteria": {
                             "true": "The news is material: earnings, M&A, guidance changes, regulatory actions or major contracts that could move the stock.",
                             "false": "The news is not material: routine announcements, opinion pieces or general market commentary."}},
        },
        "truth_map": {"direction": "direction", "material": "material"},
        "pool": [
            ({"ticker": "ACME", "source": "wire",
              "text": "ACME beats Q2 estimates by 18% and raises full-year guidance, citing record enterprise demand."},
             {"direction": "positive", "material": True}),
            ({"ticker": "BLDR", "source": "wire",
              "text": "BLDR shares face downgrade as the regulator opens an investigation into its accounting practices."},
             {"direction": "negative", "material": True}),
            ({"ticker": "CRLN", "source": "blog",
              "text": "CRLN's CEO appeared on an industry podcast to discuss long-term trends in logistics automation."},
             {"direction": "neutral", "material": False}),
            ({"ticker": "DNVT", "source": "wire",
              "text": "DNVT announces acquisition of a smaller rival for $2.1B, expanding its footprint in Europe."},
             {"direction": "positive", "material": True}),
            ({"ticker": "EMBR", "source": "wire",
              "text": "EMBR warns of a $90M writedown on its battery program and cuts its dividend."},
             {"direction": "negative", "material": True}),
            ({"ticker": "FRST", "source": "local",
              "text": "FRST opened a new regional office in {city} and hosted a community charity run last weekend."},
             {"direction": "neutral", "material": False}),
            ({"ticker": "GLBX", "source": "wire",
              "text": "GLBX secures a five-year supply contract with a major automaker, worth an estimated 12% of annual revenue."},
             {"direction": "positive", "material": True}),
            ({"ticker": "HLIX", "source": "wire",
              "text": "HLIX's phase-3 trial missed its primary endpoint; the stock halts pending the press call."},
             {"direction": "negative", "material": True}),
            ({"ticker": "INDC", "source": "blog",
              "text": "Analysts note INDC's shares traded in line with the broader index on a quiet session with no company news."},
             {"direction": "neutral", "material": False}),
            ({"ticker": "JMRK", "source": "wire",
              "text": "JMRK reports a data breach affecting 2M customers; class-action lawyers are already circling."},
             {"direction": "negative", "material": True}),
        ],
    },
    {
        "key": "sec_industry", "name": "Company sector classification", "industry": "Finance",
        "monogram": "SI", "pattern": "hierarchical classification", "prefix": "SIC",
        "blurb": "The SEC 75-industry cookbook scaled down: map company descriptions to sectors "
                 "for filings pipelines, with a diversification gate for conglomerates.",
        "header": "Business description from an annual report",
        "primary": "description", "fields": [("company", "Company")],
        "questions": {
            "sector": {"type": "choice", "instructions": "Primary sector of the company.",
                       "criteria": {
                           "technology": "This company operates in the technology sector.",
                           "healthcare": "This company operates in the healthcare sector.",
                           "energy": "This company operates in the energy sector.",
                           "financials": "This company operates in financial services.",
                           "consumer": "This company operates in consumer goods or retail.",
                           "industrials": "This company operates in industrials or manufacturing."}},
            "diversified": {"type": "boolean",
                            "instructions": "Is the company a diversified conglomerate?",
                            "criteria": {
                                "true": "The company operates across several largely unrelated sectors as a conglomerate.",
                                "false": "The company focuses on one sector or closely related lines of business."}},
        },
        "truth_map": {"sector": "sector", "diversified": "diversified"},
        "pool": [
            ({"company": "{company} Corp",
              "description": "Develops cloud infrastructure software and developer tools sold on subscription to enterprises worldwide."},
             {"sector": "technology", "diversified": False}),
            ({"company": "{company} Health",
              "description": "Operates a chain of outpatient clinics and sells diagnostic imaging equipment to hospitals."},
             {"sector": "healthcare", "diversified": False}),
            ({"company": "{company} Energy",
              "description": "Explores and produces offshore oil and gas, and is building a wind portfolio in the North Sea."},
             {"sector": "energy", "diversified": False}),
            ({"company": "{company} Financial",
              "description": "A holding company spanning retail banking, asset management and a property-casualty insurer."},
             {"sector": "financials", "diversified": True}),
            ({"company": "{company} Foods",
              "description": "Manufactures and distributes packaged snacks and beverages through grocery retailers in 30 countries."},
             {"sector": "consumer", "diversified": False}),
            ({"company": "{company} Industries",
              "description": "Builds industrial pumps, rail components and airport ground-support equipment for OEM customers."},
             {"sector": "industrials", "diversified": False}),
            ({"company": "{company} Group",
              "description": "A family-controlled group whose divisions include a hotel chain, a plastics factory, a pharmacy network and a software studio."},
             {"sector": "consumer", "diversified": True}),
            ({"company": "{company} Semi",
              "description": "Designs analog semiconductor chips for automotive suppliers; fabrication is outsourced to foundries."},
             {"sector": "technology", "diversified": False}),
            ({"company": "{company} Bio",
              "description": "A clinical-stage biotech developing antibody therapies for autoimmune diseases, pre-revenue."},
             {"sector": "healthcare", "diversified": False}),
            ({"company": "{company} Solar",
              "description": "Manufactures photovoltaic panels and runs utility-scale solar farms under long-term power purchase agreements."},
             {"sector": "energy", "diversified": False}),
        ],
    },
    # -----------------------------------------------------------------------
    # Insurance
    # -----------------------------------------------------------------------
    {
        "key": "policy_change", "name": "Policy change routing", "industry": "InsurTech",
        "monogram": "PC", "pattern": "underwriting gate", "prefix": "PCH",
        "blurb": "Separate administrative edits from risk changes: address updates auto-apply "
                 "while coverage increases route to underwriting — zero queue for the trivial 80%.",
        "header": "Policy change request from a customer",
        "primary": "request_text", "fields": [("policy", "Policy"), ("product", "Product")],
        "questions": {
            "needs_underwriting": {"type": "boolean",
                                   "instructions": "Does the change need underwriting?",
                                   "criteria": {
                                       "true": "The change needs underwriting because it alters risk: higher coverage, new insured items, business use, or health and status changes.",
                                       "false": "The change is administrative: address, name, billing, beneficiary or contact-detail edits that do not alter risk."}},
            "route": {"type": "choice", "instructions": "Processing route.",
                      "criteria": {
                          "auto": "The change should be auto-applied because it is administrative.",
                          "underwriting": "The change should go to underwriting because it alters the risk.",
                          "review": "The change should be declined pending review because it signals adverse selection."}},
        },
        "truth_map": {"needs_underwriting": "needs_underwriting", "route": "route"},
        "pool": [
            ({"policy": "POL-{n}", "product": "home",
              "request_text": "We moved apartments last week; please update the insured address to {n} Birch Lane, {city}."},
             {"needs_underwriting": False, "route": "auto"}),
            ({"policy": "POL-{n}", "product": "auto",
              "request_text": "I started driving for a rideshare platform on weekends. Please extend my cover to include commercial ride-hailing use."},
             {"needs_underwriting": True, "route": "underwriting"}),
            ({"policy": "POL-{n}", "product": "life",
              "request_text": "Please change the beneficiary from my ex-spouse to my daughter, {name}."},
             {"needs_underwriting": False, "route": "auto"}),
            ({"policy": "POL-{n}", "product": "home",
              "request_text": "We finished the basement renovation and bought jewellery worth about EUR 40,000; increase contents coverage accordingly."},
             {"needs_underwriting": True, "route": "underwriting"}),
            ({"policy": "POL-{n}", "product": "auto",
              "request_text": "My billing email changed; update it to the new address on file with my employer."},
             {"needs_underwriting": False, "route": "auto"}),
            ({"policy": "POL-{n}", "product": "health",
              "request_text": "I was diagnosed with a chronic condition last month and want to double my hospital coverage before the surgery."},
             {"needs_underwriting": True, "route": "review"}),
            ({"policy": "POL-{n}", "product": "auto",
              "request_text": "Adding my 17-year-old son as a named driver on the family policy next month."},
             {"needs_underwriting": True, "route": "underwriting"}),
            ({"policy": "POL-{n}", "product": "home",
              "request_text": "Correct the spelling of my surname on all documents: it's Kowalski, not Kowalsky."},
             {"needs_underwriting": False, "route": "auto"}),
            ({"policy": "POL-{n}", "product": "business",
              "request_text": "We now store customer servers in our warehouse; please add equipment-all-risk cover for third-party hardware."},
             {"needs_underwriting": True, "route": "underwriting"}),
            ({"policy": "POL-{n}", "product": "auto",
              "request_text": "Switch my payment method from credit card to direct debit, same amount, same date."},
             {"needs_underwriting": False, "route": "auto"}),
        ],
    },
    {
        "key": "claim_docs", "name": "Claim document check", "industry": "InsurTech",
        "monogram": "CD", "pattern": "document-quality gate", "prefix": "CDO",
        "blurb": "Before an adjuster opens a claim file, gate on document quality: readable, "
                 "complete, matching — or back to the claimant / to fraud referral.",
        "header": "Document review notes for a claim file",
        "primary": "notes", "fields": [("claim", "Claim"), ("doc_type", "Doc")],
        "questions": {
            "doc_issue": {"type": "boolean",
                          "instructions": "Does the document have quality issues?",
                          "criteria": {
                              "true": "The document has issues: illegible scans, missing pages, a different claimant's details, or expired paperwork.",
                              "false": "The document is complete, legible and matches the claim file."}},
            "status": {"type": "choice", "instructions": "File status.",
                       "criteria": {
                           "ready": "The claim file is ready to assess because the documents are complete and consistent.",
                           "resubmit": "The claim file needs resubmission because documents are missing or unreadable.",
                           "fraud_referral": "The claim file needs a fraud referral because documents look forged or mismatched."}},
        },
        "truth_map": {"doc_issue": "doc_issue", "status": "status"},
        "pool": [
            ({"claim": "CLM-{n}", "doc_type": "repair estimate",
              "notes": "Estimate is legible, dated within the incident window, repair shop details match the reported damage, all three pages present."},
             {"doc_issue": False, "status": "ready"}),
            ({"claim": "CLM-{n}", "doc_type": "police report",
              "notes": "The uploaded scan is blurred beyond readability; only the header is legible. Claimant says the original is fine."},
             {"doc_issue": True, "status": "resubmit"}),
            ({"claim": "CLM-{n}", "doc_type": "medical certificate",
              "notes": "Certificate names a different person than the policyholder and predates the policy start date by two years."},
             {"doc_issue": True, "status": "fraud_referral"}),
            ({"claim": "CLM-{n}", "doc_type": "photos",
              "notes": "Twelve timestamped photos show the reported damage from multiple angles; EXIF dates match the incident date."},
             {"doc_issue": False, "status": "ready"}),
            ({"claim": "CLM-{n}", "doc_type": "invoice",
              "notes": "Invoice pages 2-5 are missing; only the summary page was uploaded."},
             {"doc_issue": True, "status": "resubmit"}),
            ({"claim": "CLM-{n}", "doc_type": "proof of ownership",
              "notes": "Original purchase receipt with serial number matching the claimed item, store stamp visible."},
             {"doc_issue": False, "status": "ready"}),
            ({"claim": "CLM-{n}", "doc_type": "bank statement",
              "notes": "The statement appears edited: font inconsistency around the balance line and a metadata timestamp after the submission."},
             {"doc_issue": True, "status": "fraud_referral"}),
            ({"claim": "CLM-{n}", "doc_type": "ID copy",
              "notes": "Passport copy is clear, unexpired, and the name matches the policy exactly."},
             {"doc_issue": False, "status": "ready"}),
            ({"claim": "CLM-{n}", "doc_type": "repair estimate",
              "notes": "Two estimates for the same damage from the same shop with identical numbers but different dates — one looks backdated."},
             {"doc_issue": True, "status": "fraud_referral"}),
            ({"claim": "CLM-{n}", "doc_type": "weather report",
              "notes": "Official meteorological report confirms hail at the claim address on the incident date; supports the roof damage claim."},
             {"doc_issue": False, "status": "ready"}),
        ],
    },
    {
        "key": "renewal_risk", "name": "Broker renewal notes", "industry": "InsurTech",
        "monogram": "RW", "pattern": "renewal retention", "prefix": "RNW",
        "blurb": "Mine broker renewal notes for churn signals and cross-sell openings so retention "
                 "teams call the right accounts before the renewal date, not after.",
        "header": "Renewal note from the broker about an expiring policy",
        "primary": "note", "fields": [("premium", "Premium"), ("claims_3y", "Claims 3y"),
                                      ("tenure_years", "Tenure")],
        "questions": {
            "churn_risk": {"type": "boolean",
                           "instructions": "Is the renewal at risk?",
                           "criteria": {
                               "true": "The note signals the customer may not renew: price shopping, dissatisfaction, downsizing or competitor mentions.",
                               "false": "The note signals a likely renewal: satisfaction, expansion or routine continuation."}},
            "cross_sell": {"type": "boolean",
                           "instructions": "Is there a cross-sell opening?",
                           "criteria": {
                               "true": "The note contains an opening to offer additional coverage or products.",
                               "false": "The note contains no natural opening for additional products."}},
        },
        "truth_map": {"churn_risk": "churn_risk", "cross_sell": "cross_sell"},
        "pool": [
            ({"premium": "EUR {amount}", "claims_3y": 0, "tenure_years": 7,
              "note": "Client is happy with the claims handling this year and asked about adding cyber coverage for their new e-commerce arm."},
             {"churn_risk": False, "cross_sell": True}),
            ({"premium": "EUR {amount}", "claims_3y": 2, "tenure_years": 3,
              "note": "Client received a quote 20% cheaper from a competitor and is 'seriously considering' it unless we can move on price."},
             {"churn_risk": True, "cross_sell": False}),
            ({"premium": "EUR {amount}", "claims_3y": 0, "tenure_years": 12,
              "note": "Routine renewal, no changes requested. Client mentioned they just opened a second location in {city}."},
             {"churn_risk": False, "cross_sell": True}),
            ({"premium": "EUR {amount}", "claims_3y": 4, "tenure_years": 2,
              "note": "Client frustrated by the last claim's slow payout and says they will not renew if the process repeats."},
             {"churn_risk": True, "cross_sell": False}),
            ({"premium": "EUR {amount}", "claims_3y": 1, "tenure_years": 5,
              "note": "Client is downsizing office space and asked to reduce the property schedule; also inquired about directors & officers cover after a board change."},
             {"churn_risk": False, "cross_sell": True}),
            ({"premium": "EUR {amount}", "claims_3y": 0, "tenure_years": 9,
              "note": "Client confirmed the renewal budget is approved internally. No coverage changes, just send the paperwork."},
             {"churn_risk": False, "cross_sell": False}),
            ({"premium": "EUR {amount}", "claims_3y": 3, "tenure_years": 1,
              "note": "Client's business is winding down the insured operations; they hinted at cancelling the fleet policy entirely."},
             {"churn_risk": True, "cross_sell": False}),
            ({"premium": "EUR {amount}", "claims_3y": 0, "tenure_years": 6,
              "note": "Client just acquired a small logistics firm and wants to discuss folding their vehicles into the existing fleet policy."},
             {"churn_risk": False, "cross_sell": True}),
            ({"premium": "EUR {amount}", "claims_3y": 1, "tenure_years": 4,
              "note": "Client is upset about the premium increase and asked us to re-market the risk to three other insurers."},
             {"churn_risk": True, "cross_sell": False}),
            ({"premium": "EUR {amount}", "claims_3y": 0, "tenure_years": 8,
              "note": "Renewal meeting went well; client praised the loss-prevention survey and will renew as usual."},
             {"churn_risk": False, "cross_sell": False}),
        ],
    },
    # -----------------------------------------------------------------------
    # Health / life sciences (operational, non-diagnostic)
    # -----------------------------------------------------------------------
    {
        "key": "appointment_triage", "name": "Appointment request triage", "industry": "Healthcare ops",
        "monogram": "AT", "pattern": "scheduling triage", "prefix": "APT",
        "disclaimer": "Operational scheduling demo only — never a diagnosis or medical advice. "
                      "Real deployments require clinical governance and human oversight.",
        "blurb": "Sort appointment requests into urgent same-day slots, routine in-person, video "
                 "or nurse-call — operational queue management, explicitly not medical advice.",
        "header": "Appointment request message from a patient (operational routing only, not a diagnosis)",
        "primary": "message", "fields": [("patient_age", "Age"), ("preferred_date", "Preferred")],
        "questions": {
            "urgent_slot": {"type": "boolean",
                            "instructions": "Does the request warrant an urgent same-day slot?",
                            "criteria": {
                                "true": "The request describes worsening or potentially serious symptoms that warrant an urgent same-day appointment.",
                                "false": "The request describes a stable, routine matter suitable for a normal appointment."}},
            "visit_type": {"type": "choice", "instructions": "Best visit type.",
                           "criteria": {
                               "in_person": "This request needs an in-person visit.",
                               "video": "This request can be handled by a video visit.",
                               "nurse_call": "This request can be handled by a nurse phone call."}},
        },
        "truth_map": {"urgent_slot": "urgent_slot", "visit_type": "visit_type"},
        "pool": [
            ({"patient_age": 44, "preferred_date": "next week",
              "message": "I need my annual blood-work review and a prescription refill for my thyroid medication. Feeling fine otherwise."},
             {"urgent_slot": False, "visit_type": "video"}),
            ({"patient_age": 67, "preferred_date": "today",
              "message": "Since this morning I have chest tightness when climbing stairs and my blood pressure reading was 185/110."},
             {"urgent_slot": True, "visit_type": "in_person"}),
            ({"patient_age": 29, "preferred_date": "anytime",
              "message": "Question about the dosage timing of my current medication — the leaflet contradicts what the pharmacist said."},
             {"urgent_slot": False, "visit_type": "nurse_call"}),
            ({"patient_age": 8, "preferred_date": "today",
              "message": "My son has had a fever of 39.5 for two days with a new rash that doesn't fade under pressure. He's been very drowsy."},
             {"urgent_slot": True, "visit_type": "in_person"}),
            ({"patient_age": 52, "preferred_date": "this month",
              "message": "Mole on my back changed color recently; would like the dermatology check you mentioned last year."},
             {"urgent_slot": False, "visit_type": "in_person"}),
            ({"patient_age": 35, "preferred_date": "flexible",
              "message": "Requesting the standard vaccination schedule for my newborn and a lactation consultation."},
             {"urgent_slot": False, "visit_type": "nurse_call"}),
            ({"patient_age": 71, "preferred_date": "asap",
              "message": "Fell in the bathroom an hour ago, hit my head briefly, now on blood thinners and feeling nauseous."},
             {"urgent_slot": True, "visit_type": "in_person"}),
            ({"patient_age": 23, "preferred_date": "next week",
              "message": "Persistent cough for six weeks after a cold; no fever, but it won't go away and I'd like it checked."},
             {"urgent_slot": False, "visit_type": "in_person"}),
            ({"patient_age": 48, "preferred_date": "today",
              "message": "Sudden severe abdominal pain since two hours ago, radiating to the back, with vomiting."},
             {"urgent_slot": True, "visit_type": "in_person"}),
            ({"patient_age": 31, "preferred_date": "flexible",
              "message": "Follow-up on last month's lab results and renewing the physio referral — all paperwork is in the portal."},
             {"urgent_slot": False, "visit_type": "video"}),
        ],
    },
    {
        "key": "pharmacovigilance", "name": "Adverse-event seriousness screen",
        "industry": "Life sciences", "monogram": "PV", "pattern": "safety signal gating", "prefix": "PHV",
        "disclaimer": "Synthetic demo of intake screening only — real pharmacovigilance requires "
                      "validated systems, medically trained reviewers and regulatory workflows.",
        "blurb": "First-pass seriousness and causality screening of adverse-event narratives so "
                 "safety teams meet reporting clocks — the intake triage layer, not the medical judgment.",
        "header": "Adverse event report narrative",
        "primary": "narrative", "fields": [("drug", "Drug"), ("reporter", "Reporter"),
                                           ("onset_days", "Onset")],
        "questions": {
            "serious": {"type": "boolean",
                        "instructions": "Is the event serious by ICH-style criteria?",
                        "criteria": {
                            "true": "The event is serious: it mentions hospitalization, a life-threatening reaction, permanent damage, or death.",
                            "false": "The event is non-serious: mild, transient symptoms that resolved without medical intervention."}},
            "causality": {"type": "choice", "instructions": "Reported causality assessment.",
                          "criteria": {
                              "likely": "The drug is the likely cause of the event.",
                              "possible": "The drug is a possible cause of the event.",
                              "unlikely": "The event is likely unrelated to the drug."}},
        },
        "truth_map": {"serious": "serious", "causality": "causality"},
        "pool": [
            ({"drug": "Cardiolex 20mg", "reporter": "physician", "onset_days": 2,
              "narrative": "Patient hospitalized with acute liver injury five days after starting the drug; enzymes ten times the upper limit, no other hepatotoxic co-medication."},
             {"serious": True, "causality": "likely"}),
            ({"drug": "Dermaclear gel", "reporter": "consumer", "onset_days": 1,
              "narrative": "Mild skin redness at the application site for a few hours, resolved on its own without treatment."},
             {"serious": False, "causality": "possible"}),
            ({"drug": "Neurocalm 5mg", "reporter": "physician", "onset_days": 14,
              "narrative": "Patient experienced a fall and fractured a wrist while also taking two other sedating medications and reporting dizziness before the event."},
             {"serious": True, "causality": "possible"}),
            ({"drug": "GastrEase", "reporter": "consumer", "onset_days": 1,
              "narrative": "Headache on the first day of use that went away after a glass of water; the patient had skipped lunch and had a history of migraines."},
             {"serious": False, "causality": "unlikely"}),
            ({"drug": "Immunorix", "reporter": "pharmacist", "onset_days": 3,
              "narrative": "Anaphylactic reaction within thirty minutes of the infusion; treated with epinephrine in the emergency department, patient recovered fully."},
             {"serious": True, "causality": "likely"}),
            ({"drug": "PainAway Plus", "reporter": "consumer", "onset_days": 2,
              "narrative": "Upset stomach for one evening after the first dose; no other symptoms and the patient continued the course without issue."},
             {"serious": False, "causality": "possible"}),
            ({"drug": "RespiClear inhaler", "reporter": "physician", "onset_days": 30,
              "narrative": "Patient developed a rash two days after a viral infection unrelated to the inhaler schedule; dermatologist attributed it to the virus."},
             {"serious": False, "causality": "unlikely"}),
            ({"drug": "Hemostop", "reporter": "physician", "onset_days": 5,
              "narrative": "Life-threatening bleeding episode in a patient on the drug with interacting anticoagulant started by another department."},
             {"serious": True, "causality": "possible"}),
            ({"drug": "Somnwell", "reporter": "consumer", "onset_days": 7,
              "narrative": "Next-day grogginess for the first week, then adapted; no medical care sought, patient kept using the product."},
             {"serious": False, "causality": "likely"}),
            ({"drug": "Vascotens", "reporter": "physician", "onset_days": 60,
              "narrative": "Persistent dry cough began two months into therapy, a documented class effect; resolved after switching per the label guidance."},
             {"serious": False, "causality": "likely"}),
        ],
    },
    {
        "key": "trial_screening", "name": "Trial volunteer screening", "industry": "Life sciences",
        "monogram": "TS", "pattern": "eligibility gating", "prefix": "TRS",
        "disclaimer": "Synthetic demo only — eligibility decisions in real trials follow the "
                      "protocol and qualified medical staff.",
        "blurb": "Pre-screen volunteer notes against stated inclusion/exclusion criteria so "
                 "coordinators schedule confirmatory visits only for plausible matches.",
        "header": "Volunteer screening note for a clinical trial",
        "primary": "note", "fields": [("trial", "Trial"), ("age", "Age")],
        "questions": {
            "meets_inclusion": {"type": "boolean",
                                "instructions": "Does the volunteer meet the stated criteria?",
                                "criteria": {
                                    "true": "The volunteer meets the inclusion criteria stated in the note: the age range, the condition status and no exclusion factors.",
                                    "false": "The volunteer hits an exclusion criterion or falls outside the stated inclusion range."}},
            "action": {"type": "choice", "instructions": "Coordinator action.",
                       "criteria": {
                           "enroll": "The coordinator should enroll the volunteer because every criterion is clearly met.",
                           "confirm_visit": "The coordinator should schedule a confirmatory visit because the match looks good but needs verification.",
                           "screen_out": "The coordinator should screen out the volunteer because an exclusion criterion applies."}},
        },
        "truth_map": {"meets_inclusion": "meets_inclusion", "action": "action"},
        "pool": [
            ({"trial": "TRIAL-{n} (type 2 diabetes, age 30-70)", "age": 54,
              "note": "Diagnosed type 2 diabetes four years ago, HbA1c 7.8%, on metformin only, no kidney disease, no recent cardiovascular events. Motivated, lives nearby."},
             {"meets_inclusion": True, "action": "confirm_visit"}),
            ({"trial": "TRIAL-{n} (type 2 diabetes, age 30-70)", "age": 27,
              "note": "Type 2 diabetes diagnosed last year; the candidate is below the protocol's minimum age of 30."},
             {"meets_inclusion": False, "action": "screen_out"}),
            ({"trial": "TRIAL-{n} (mild hypertension, age 40-75)", "age": 61,
              "note": "Average home readings 148/92 over six weeks, no medication, non-smoker, no diabetes. Meets every listed criterion."},
             {"meets_inclusion": True, "action": "enroll"}),
            ({"trial": "TRIAL-{n} (mild hypertension, age 40-75)", "age": 58,
              "note": "Blood pressure in range but the volunteer is currently pregnant, which the protocol excludes."},
             {"meets_inclusion": False, "action": "screen_out"}),
            ({"trial": "TRIAL-{n} (seasonal allergy, age 18-65)", "age": 33,
              "note": "Doctor-diagnosed seasonal allergic rhinitis for ten years, symptomatic each spring, otherwise healthy, no immunotherapy in the last year."},
             {"meets_inclusion": True, "action": "confirm_visit"}),
            ({"trial": "TRIAL-{n} (seasonal allergy, age 18-65)", "age": 40,
              "note": "Allergy symptoms present but the volunteer started immunotherapy three months ago, an exclusion per the protocol."},
             {"meets_inclusion": False, "action": "screen_out"}),
            ({"trial": "TRIAL-{n} (insomnia, age 25-60)", "age": 47,
              "note": "Chronic insomnia for three years confirmed by sleep diary, no sleep medication in the past month, no shift work, no untreated apnea."},
             {"meets_inclusion": True, "action": "enroll"}),
            ({"trial": "TRIAL-{n} (insomnia, age 25-60)", "age": 66,
              "note": "Sleep complaints and willing to participate, but above the protocol's maximum age and currently taking a sedative nightly."},
             {"meets_inclusion": False, "action": "screen_out"}),
            ({"trial": "TRIAL-{n} (knee osteoarthritis, age 45-80)", "age": 59,
              "note": "Radiographic knee OA grade 2, pain on most days for six months, can walk unaided, no joint injection in the last three months."},
             {"meets_inclusion": True, "action": "confirm_visit"}),
            ({"trial": "TRIAL-{n} (knee osteoarthritis, age 45-80)", "age": 52,
              "note": "Knee pain after a sports injury last month; imaging shows a meniscal tear rather than osteoarthritis."},
             {"meets_inclusion": False, "action": "screen_out"}),
        ],
    },
    # -----------------------------------------------------------------------
    # Legal / compliance / privacy
    # -----------------------------------------------------------------------
    {
        "key": "nda_check", "name": "NDA clause screening", "industry": "Legal ops",
        "monogram": "NA", "pattern": "clause screening", "prefix": "NDA",
        "blurb": "High-volume NDA intake: mutuality and perpetual-obligation gates plus a risk "
                 "grade — paralegals only open the flagged minority.",
        "header": "NDA clause under review",
        "primary": "text", "fields": [("counterparty", "Counterparty"), ("section", "Section")],
        "questions": {
            "mutual": {"type": "boolean",
                       "instructions": "Are the obligations mutual?",
                       "criteria": {
                           "true": "The confidentiality obligations in this clause bind both parties equally.",
                           "false": "The confidentiality obligations in this clause bind only one party."}},
            "perpetual": {"type": "boolean",
                          "instructions": "Are the obligations perpetual?",
                          "criteria": {
                              "true": "The obligations last forever or have no defined end date.",
                              "false": "The obligations expire after a defined period."}},
            "risk": {"type": "choice", "instructions": "Risk grade for the signer.",
                     "criteria": {
                         "low": "The clause risk for the signer is low because the terms are balanced and time-limited.",
                         "medium": "The clause risk for the signer is medium because one term needs attention.",
                         "high": "The clause risk for the signer is high because obligations are one-sided or perpetual."}},
        },
        "truth_map": {"mutual": "mutual", "perpetual": "perpetual", "risk": "risk"},
        "pool": [
            ({"counterparty": "{company}", "section": "Confidentiality",
              "text": "Each party shall keep the other's confidential information secret for three (3) years from disclosure and use it solely for evaluating the proposed collaboration."},
             {"mutual": True, "perpetual": False, "risk": "low"}),
            ({"counterparty": "{company}", "section": "Confidentiality",
              "text": "The Receiving Party shall hold all Disclosing Party information in strict confidence in perpetuity, with no time limit, including after termination of discussions."},
             {"mutual": False, "perpetual": True, "risk": "high"}),
            ({"counterparty": "{company}", "section": "Trade secrets",
              "text": "Both parties agree that trade-secret obligations survive indefinitely as required by law, while all other confidential information expires after five (5) years."},
             {"mutual": True, "perpetual": True, "risk": "medium"}),
            ({"counterparty": "{company}", "section": "Confidentiality",
              "text": "The Consultant shall not disclose any Company information ever, to anyone, by any means, and this obligation binds the Consultant's heirs and successors."},
             {"mutual": False, "perpetual": True, "risk": "high"}),
            ({"counterparty": "{company}", "section": "Purpose",
              "text": "Information exchanged under this agreement may be used by both parties solely for the joint marketing pilot described in Annex A, for its twelve-month duration."},
             {"mutual": True, "perpetual": False, "risk": "low"}),
            ({"counterparty": "{company}", "section": "Return of materials",
              "text": "Upon written request, the Vendor must return or destroy all customer data within ten days, and certify destruction; the Vendor's obligations continue for two years thereafter."},
             {"mutual": False, "perpetual": False, "risk": "medium"}),
            ({"counterparty": "{company}", "section": "Exclusions",
              "text": "Neither party has obligations for information that is public through no fault of its own, independently developed, or lawfully received from a third party without restriction."},
             {"mutual": True, "perpetual": False, "risk": "low"}),
            ({"counterparty": "{company}", "section": "Residuals",
              "text": "The Disclosing Party grants the Recipient unlimited residual rights to use anything retained in unaided memory, without any time limit or compensation."},
             {"mutual": False, "perpetual": True, "risk": "high"}),
        ],
    },
    {
        "key": "reg_change", "name": "Regulatory change screening", "industry": "Compliance",
        "monogram": "RG", "pattern": "applicability gating", "prefix": "RGC",
        "blurb": "Screen every regulatory update for applicability to the business and required "
                 "response speed — compliance reads only what applies, before the deadline.",
        "header": "Regulatory update summary from the compliance feed",
        "primary": "summary", "fields": [("regulator", "Regulator"), ("jurisdiction", "Jurisdiction"),
                                         ("effective", "Effective")],
        "questions": {
            "applies_to_us": {"type": "boolean",
                              "instructions": "Does the update apply to the business?",
                              "criteria": {
                                  "true": "The update applies to a payments company that operates customer accounts and card processing in the stated jurisdiction.",
                                  "false": "The update does not apply: it targets a different industry, a different jurisdiction, or exempt activities."}},
            "urgency": {"type": "choice", "instructions": "Required response.",
                        "criteria": {
                            "act_now": "The team must act before the effective date because the new rules will bind them.",
                            "plan_quarter": "The team should plan changes this quarter because the update applies but allows time.",
                            "monitor": "The team only needs to monitor the update because it does not bind them."}},
        },
        "truth_map": {"applies_to_us": "applies_to_us", "urgency": "urgency"},
        "pool": [
            ({"regulator": "Central Bank", "jurisdiction": "Ireland", "effective": "in 30 days",
              "summary": "New strong-customer-authentication exemptions and transaction-monitoring thresholds for all payment account providers operating in the state, effective within 30 days."},
             {"applies_to_us": True, "urgency": "act_now"}),
            ({"regulator": "FDA", "jurisdiction": "United States", "effective": "next year",
              "summary": "Updated labelling requirements for over-the-counter dietary supplements sold in retail packaging."},
             {"applies_to_us": False, "urgency": "monitor"}),
            ({"regulator": "FCA", "jurisdiction": "United Kingdom", "effective": "in 6 months",
              "summary": "Consumer duty reporting expansion for consumer-credit firms; payment processors without lending activity are explicitly out of scope for phase one."},
             {"applies_to_us": True, "urgency": "plan_quarter"}),
            ({"regulator": "ESMA", "jurisdiction": "EU", "effective": "in 9 months",
              "summary": "Amended transaction-reporting field validation for investment firms executing securities orders on regulated venues."},
             {"applies_to_us": False, "urgency": "monitor"}),
            ({"regulator": "FinCEN", "jurisdiction": "United States", "effective": "in 45 days",
              "summary": "Lowered suspicious-activity reporting threshold for money-services businesses handling prepaid access, with a 45-day implementation window."},
             {"applies_to_us": True, "urgency": "act_now"}),
            ({"regulator": "BaFin", "jurisdiction": "Germany", "effective": "in 12 months",
              "summary": "Draft guidance on operational-resilience testing for significant payment institutions; consultation period open, final text expected next year."},
             {"applies_to_us": True, "urgency": "plan_quarter"}),
            ({"regulator": "MAR", "jurisdiction": "Morocco", "effective": "in 3 months",
              "summary": "New licensing regime for domestic microfinance lenders operating in the Moroccan market."},
             {"applies_to_us": False, "urgency": "monitor"}),
            ({"regulator": "DPC", "jurisdiction": "Ireland", "effective": "immediately",
              "summary": "Binding decision requiring all account-servicing payment providers to honour data-portability export requests within 72 hours, effective immediately."},
             {"applies_to_us": True, "urgency": "act_now"}),
        ],
    },
    {
        "key": "sanctions_text", "name": "Sanctions nexus screening", "industry": "Compliance",
        "monogram": "SN", "pattern": "screening gate", "prefix": "SNC",
        "blurb": "Scan counterparty descriptions for sanctioned-country and listed-entity signals "
                 "before onboarding clears, reviews or blocks — name screening's semantic cousin.",
        "header": "Counterparty description from the onboarding form",
        "primary": "description", "fields": [("name", "Name"), ("country", "Country")],
        "questions": {
            "sanctions_nexus": {"type": "boolean",
                                "instructions": "Is there a sanctions nexus?",
                                "criteria": {
                                    "true": "The description mentions sanctioned countries, listed entities, embargoed trade or activities tied to sanctioned parties.",
                                    "false": "The description mentions only ordinary commercial activity in non-sanctioned places."}},
            "action": {"type": "choice", "instructions": "Screening action.",
                       "criteria": {
                           "clear": "Screening should clear the counterparty because no sanctions signals appear.",
                           "review": "Screening should send the counterparty to enhanced review because signals are ambiguous.",
                           "block": "Screening should block the counterparty because listed parties or embargoed trade appear."}},
        },
        "truth_map": {"sanctions_nexus": "sanctions_nexus", "action": "action"},
        "pool": [
            ({"name": "{company} GmbH", "country": "Germany",
              "description": "Wholesale distributor of industrial fasteners serving automotive customers in Germany and Austria for over twenty years."},
             {"sanctions_nexus": False, "action": "clear"}),
            ({"name": "{company} Trading", "country": "UAE",
              "description": "General trading company re-exporting dual-use electronic components; recent shipments routed through Iran-adjacent free zones per the bill-of-lading history."},
             {"sanctions_nexus": True, "action": "block"}),
            ({"name": "{name} Ltd", "country": "United Kingdom",
              "description": "Software consultancy delivering IT projects to NHS trusts and local councils; fully transparent ownership."},
             {"sanctions_nexus": False, "action": "clear"}),
            ({"name": "{company} OOO", "country": "Russia",
              "description": "Oilfield services firm whose ultimate beneficial owner appears on the SDN list; contracts include Rosneft subsidiaries."},
             {"sanctions_nexus": True, "action": "block"}),
            ({"name": "{company} Logistics", "country": "Turkey",
              "description": "Freight forwarder with regular lanes to Central Asia; two counterparties share addresses with entities under EU enhanced monitoring."},
             {"sanctions_nexus": True, "action": "review"}),
            ({"name": "{company} Foods", "country": "Brazil",
              "description": "Exporter of frozen poultry to Gulf states with standard halal certification and no restricted-party links."},
             {"sanctions_nexus": False, "action": "clear"}),
            ({"name": "{name} Shipping", "country": "Panama",
              "description": "Single-vessel shipping company; AIS transponder went dark for eleven days near a sanctioned oil terminal last quarter."},
             {"sanctions_nexus": True, "action": "review"}),
            ({"name": "{company} SA", "country": "France",
              "description": "Listed cosmetics manufacturer selling through retail chains across the EU; clean ownership chain."},
             {"sanctions_nexus": False, "action": "clear"}),
        ],
    },
    {
        "key": "privacy_request", "name": "Data-subject request intake", "industry": "Privacy",
        "monogram": "DS", "pattern": "DSAR classification", "prefix": "DSR",
        "blurb": "Classify the privacy@ mailbox in real time: is this a valid data-subject "
                 "request, and which clock starts — access, erasure, or rectification?",
        "header": "Incoming message to the privacy mailbox",
        "primary": "text", "fields": [("channel", "Channel")],
        "questions": {
            "valid_dsar": {"type": "boolean",
                           "instructions": "Is this a valid data-subject request?",
                           "criteria": {
                               "true": "The message is a data-subject request: it asks for access to, deletion of, correction of, or a copy of the sender's personal data.",
                               "false": "The message is not a data-subject request: it is marketing, spam, a support question, or another inquiry."}},
            "type": {"type": "choice", "instructions": "Request type.",
                     "criteria": {
                         "access": "The request asks for access to or a copy of personal data.",
                         "deletion": "The request asks for deletion of personal data.",
                         "correction": "The request asks for correction or portability of personal data.",
                         "not_a_request": "The message is not a data request."}},
        },
        "truth_map": {"valid_dsar": "valid_dsar", "type": "type"},
        "pool": [
            ({"channel": "email",
              "text": "Under GDPR Article 15, please provide a copy of all personal data you hold about me, including processing purposes and recipients."},
             {"valid_dsar": True, "type": "access"}),
            ({"channel": "web form",
              "text": "I closed my account last year. Please erase all my personal data from your systems and confirm when done."},
             {"valid_dsar": True, "type": "deletion"}),
            ({"channel": "email",
              "text": "My surname changed after marriage. Please update it everywhere, and send my data to my new provider in a machine-readable format."},
             {"valid_dsar": True, "type": "correction"}),
            ({"channel": "email",
              "text": "URGENT BUSINESS OPPORTUNITY: expand your customer base with our lead database, special price this week only, reply now."},
             {"valid_dsar": False, "type": "not_a_request"}),
            ({"channel": "web form",
              "text": "How do I change the font size in the mobile app? The settings menu is confusing."},
             {"valid_dsar": False, "type": "not_a_request"}),
            ({"channel": "email",
              "text": "I am a journalist writing about your company. Which of my data do you store, and who did you share it with?"},
             {"valid_dsar": True, "type": "access"}),
            ({"channel": "phone transcript",
              "text": "Caller wants everything deleted — app account, marketing profile, and the analytics records — and asked for written confirmation."},
             {"valid_dsar": True, "type": "deletion"}),
            ({"channel": "email",
              "text": "Please unsubscribe me from the newsletter, I get three emails a week and never signed up."},
             {"valid_dsar": False, "type": "not_a_request"}),
            ({"channel": "web form",
              "text": "Your records show my birth date wrong, which blocked my verification. Fix it to 12 March 1988 and confirm."},
             {"valid_dsar": True, "type": "correction"}),
            ({"channel": "email",
              "text": "We are a law firm. Send us the complete data inventory for your entire customer base within 48 hours. (bulk request from a third party, no authority documents)"},
             {"valid_dsar": False, "type": "not_a_request"}),
        ],
    },
]
