"""Spec-driven use-case packs (2/4): support/CX, commerce, fintech."""
from __future__ import annotations

PACKS_B: list[dict] = [
    # -----------------------------------------------------------------------
    # Support / CX
    # -----------------------------------------------------------------------
    {
        "key": "chat_intent", "name": "Live-chat intent routing", "industry": "Customer support",
        "monogram": "CI", "pattern": "intent routing", "prefix": "CHT",
        "blurb": "First-hop routing for live chat: which queue owns the message, and is the "
                 "customer already demanding a human? Decided before the bot's first reply.",
        "header": "Live-chat message from a customer",
        "primary": "text", "fields": [("page", "Page")],
        "questions": {
            "intent": {"type": "choice", "instructions": "Primary intent of the message.",
                       "criteria": {
                           "order_status": "The customer is asking about the status of an order or delivery.",
                           "refund": "The customer is requesting a refund or disputing a charge.",
                           "tech_help": "The customer needs technical help with the product.",
                           "sales": "The customer is interested in buying, upgrading or comparing plans."}},
            "wants_human": {"type": "boolean",
                            "instructions": "Does the customer demand a human agent?",
                            "criteria": {
                                "true": "The customer explicitly asks for a human agent or is frustrated enough to demand one.",
                                "false": "The customer is fine interacting with the bot for now."}},
        },
        "truth_map": {"intent": "intent", "wants_human": "wants_human"},
        "pool": [
            ({"page": "/orders", "text": "Where is my package? Tracking hasn't moved in four days, order {n}."},
             {"intent": "order_status", "wants_human": False}),
            ({"page": "/billing", "text": "I was charged twice this month. I want the second charge refunded now."},
             {"intent": "refund", "wants_human": False}),
            ({"page": "/app", "text": "The mobile app keeps crashing when I open the reports tab. Phone is a Pixel 9."},
             {"intent": "tech_help", "wants_human": False}),
            ({"page": "/pricing", "text": "We're a team of {n} — what would the business plan cost annually, and do you support SSO?"},
             {"intent": "sales", "wants_human": False}),
            ({"page": "/billing", "text": "This is the third time I ask about my refund. Enough bots. Get me a human being immediately."},
             {"intent": "refund", "wants_human": True}),
            ({"page": "/orders", "text": "I want to speak to a real person about the missing items in my delivery. Transfer me now."},
             {"intent": "order_status", "wants_human": True}),
            ({"page": "/app", "text": "Nobody at this company can fix the sync bug and your chatbot keeps repeating itself. Manager. Now."},
             {"intent": "tech_help", "wants_human": True}),
            ({"page": "/home", "text": "Hi! Quick question: does the trial need a credit card?"},
             {"intent": "sales", "wants_human": False}),
            ({"page": "/app", "text": "How do I reset the two-factor authenticator? I got a new phone."},
             {"intent": "tech_help", "wants_human": False}),
            ({"page": "/orders", "text": "Can I still change the delivery address for order {n}? It ships tomorrow."},
             {"intent": "order_status", "wants_human": False}),
            ({"page": "/billing", "text": "Your competitor offers the same for half the price — can you match it before I decide? Preferably a human rep."},
             {"intent": "sales", "wants_human": True}),
            ({"page": "/billing", "text": "The invoice shows the wrong company name, please reissue it."},
             {"intent": "refund", "wants_human": False}),
        ],
    },
    {
        "key": "emotion_detect", "name": "Customer emotion detection", "industry": "CX",
        "monogram": "ED", "pattern": "sentiment family", "prefix": "EMO",
        "blurb": "The BTZSC 'emotion' family in production shape: grade the customer's emotional "
                 "state and decide whether the reply must open with de-escalation.",
        "header": "Customer message to the support bot",
        "primary": "text", "fields": [("channel", "Channel")],
        "questions": {
            "emotion": {"type": "choice", "instructions": "Dominant emotion in the message.",
                        "criteria": {
                            "angry": "The customer sounds angry.",
                            "frustrated": "The customer sounds frustrated but controlled.",
                            "neutral": "The customer sounds neutral.",
                            "happy": "The customer sounds happy."}},
            "de_escalate": {"type": "boolean",
                            "instructions": "Should the reply start with de-escalation?",
                            "criteria": {
                                "true": "The reply should open with an apology and empathy before any procedure, because the customer is angry or close to it.",
                                "false": "The reply can go straight to the answer without an apology-first opening."}},
        },
        "truth_map": {"emotion": "emotion", "de_escalate": "de_escalate"},
        "pool": [
            ({"channel": "chat", "text": "ABSOLUTELY UNACCEPTABLE. Five days without a reply and now you close the ticket?! I am beyond furious."},
             {"emotion": "angry", "de_escalate": True}),
            ({"channel": "email", "text": "This is the second time the export fails. It's really getting in the way of my deadline, quite frustrating."},
             {"emotion": "frustrated", "de_escalate": False}),
            ({"channel": "chat", "text": "Hello, could you tell me how to change the billing email? Thanks."},
             {"emotion": "neutral", "de_escalate": False}),
            ({"channel": "email", "text": "Just wanted to say the new onboarding flow is lovely — set up my whole team in ten minutes. Great work!"},
             {"emotion": "happy", "de_escalate": False}),
            ({"channel": "chat", "text": "You people are running a scam. I will chargeback and post everywhere unless I get my money TODAY."},
             {"emotion": "angry", "de_escalate": True}),
            ({"channel": "chat", "text": "The sync is a bit slow this week, is that known? Not urgent, just noting it."},
             {"emotion": "neutral", "de_escalate": False}),
            ({"channel": "email", "text": "Third attempt, still broken. I've lost a morning to this and I'm losing patience."},
             {"emotion": "frustrated", "de_escalate": True}),
            ({"channel": "chat", "text": "Thank you so much — that fixed it instantly! You made my day."},
             {"emotion": "happy", "de_escalate": False}),
            ({"channel": "email", "text": "Please confirm the receipt number for our accounting. Standard procedure, no rush."},
             {"emotion": "neutral", "de_escalate": False}),
            ({"channel": "chat", "text": "I've been a loyal customer for years and this is how I'm treated? Disgusting service. Fix it or I'm gone."},
             {"emotion": "angry", "de_escalate": True}),
        ],
    },
    {
        "key": "churn_risk", "name": "Churn-risk detection", "industry": "CX",
        "monogram": "CR", "pattern": "retention gating", "prefix": "CHN",
        "blurb": "Combine the account snapshot with the latest message: is this customer about to "
                 "leave, and which retention play fits? Success teams work the flagged list first.",
        "header": "Customer health snapshot with the latest support message",
        "primary": "message", "fields": [("tenure_months", "Tenure"), ("usage_trend", "Usage"),
                                          ("plan", "Plan")],
        "questions": {
            "at_risk": {"type": "boolean", "instructions": "Is the customer at churn risk?",
                        "criteria": {
                            "true": "This customer shows churn risk: falling usage, cancellation language, competitor mentions or unresolved anger.",
                            "false": "This customer shows no churn risk; usage is stable and the tone is neutral or positive."}},
            "play": {"type": "choice", "instructions": "Retention play.",
                     "criteria": {
                         "save_offer": "The success team should send a save offer because the customer is actively leaving.",
                         "check_in": "The success team should schedule a check-in call because the customer is unhappy but reachable.",
                         "none": "The success team needs no action because the customer is stable or growing."}},
        },
        "truth_map": {"at_risk": "at_risk", "play": "play"},
        "pool": [
            ({"tenure_months": 34, "usage_trend": "down 60% in 8 weeks", "plan": "business",
              "message": "We've mostly moved to {company}'s platform for this. Planning not to renew unless something changes dramatically."},
             {"at_risk": True, "play": "save_offer"}),
            ({"tenure_months": 8, "usage_trend": "down 25% in 4 weeks", "plan": "pro",
              "message": "The new pricing confuses me and honestly I'm evaluating options. Can we talk about what we actually use?"},
             {"at_risk": True, "play": "check_in"}),
            ({"tenure_months": 22, "usage_trend": "flat", "plan": "pro",
              "message": "Quick question about API rate limits before our launch next month."},
             {"at_risk": False, "play": "none"}),
            ({"tenure_months": 41, "usage_trend": "up 30%", "plan": "enterprise",
              "message": "Rolling you out to two more teams — can we get a quote for 50 extra seats?"},
             {"at_risk": False, "play": "none"}),
            ({"tenure_months": 3, "usage_trend": "down 80% after week one", "plan": "pro",
              "message": "I can't get the import to work and support never answered. Probably cancelling."},
             {"at_risk": True, "play": "save_offer"}),
            ({"tenure_months": 15, "usage_trend": "flat", "plan": "business",
              "message": "Everything is running smoothly. We might explore the analytics add-on next quarter."},
             {"at_risk": False, "play": "none"}),
            ({"tenure_months": 27, "usage_trend": "down 40%", "plan": "business",
              "message": "Budget review coming up and your line item is on the chopping block. What can you do for us?"},
             {"at_risk": True, "play": "save_offer"}),
            ({"tenure_months": 11, "usage_trend": "up 10%", "plan": "pro",
              "message": "Feature request: dark mode for the dashboard. Otherwise very happy with the product."},
             {"at_risk": False, "play": "none"}),
            ({"tenure_months": 6, "usage_trend": "down 50%", "plan": "pro",
              "message": "The onboarding promised reports we still can't build. Disappointed — need a call to see if this can work."},
             {"at_risk": True, "play": "check_in"}),
            ({"tenure_months": 52, "usage_trend": "flat", "plan": "enterprise",
              "message": "Renewal paperwork attached; legal had two small redlines, nothing major."},
             {"at_risk": False, "play": "none"}),
        ],
    },
    {
        "key": "faq_match", "name": "FAQ answer matching", "industry": "Customer support",
        "monogram": "FQ", "pattern": "entailment matching (NLI-native)", "prefix": "FAQ",
        "blurb": "Does this FAQ article actually answer the incoming question? Pure entailment — "
                 "the bot answers, offers a partial link, or routes to a human.",
        "header": "Incoming question matched against one FAQ article",
        "primary": "question", "label_primary": "Question",
        "footer_fields": ["faq_answer"], "fields": [("faq_id", "FAQ")],
        "questions": {
            "answered": {"type": "boolean",
                         "instructions": "Does the FAQ article answer the question?",
                         "criteria": {
                             "true": "The FAQ article contains the information needed to answer the question.",
                             "false": "The FAQ article does not contain the information needed to answer the question."}},
            "action": {"type": "choice", "instructions": "Bot action.",
                       "criteria": {
                           "answer": "The bot should answer with this FAQ article because it fully answers the question.",
                           "partial": "The bot should offer this FAQ article as a partial answer because it is related but incomplete.",
                           "human": "The bot should route the question to a human because no FAQ article answers it."}},
        },
        "truth_map": {"answered": "answered", "action": "action"},
        "pool": [
            ({"faq_id": "F-{n}", "question": "How do I change my billing email address?",
              "faq_answer": "To update the billing email, go to Settings, then Billing, and edit the contact email. Changes apply to future invoices immediately."},
             {"answered": True, "action": "answer"}),
            ({"faq_id": "F-{n}", "question": "Can I get a discount for annual payment?",
              "faq_answer": "Our password policy requires at least twelve characters and supports single sign-on on business plans."},
             {"answered": False, "action": "human"}),
            ({"faq_id": "F-{n}", "question": "What file formats can I export?",
              "faq_answer": "Exports are available in CSV and JSON. XLSX export is on the roadmap but not available yet."},
             {"answered": True, "action": "answer"}),
            ({"faq_id": "F-{n}", "question": "Do you support XLSX export?",
              "faq_answer": "Exports are available in CSV and JSON. XLSX export is on the roadmap but not available yet."},
             {"answered": True, "action": "answer"}),
            ({"faq_id": "F-{n}", "question": "Why was my last invoice higher than usual?",
              "faq_answer": "Invoices are issued on the first of each month and can be paid by card or bank transfer."},
             {"answered": False, "action": "human"}),
            ({"faq_id": "F-{n}", "question": "Is there a limit on team members?",
              "faq_answer": "The starter plan includes five seats. Additional seats can be purchased, and enterprise plans have no seat cap."},
             {"answered": True, "action": "answer"}),
            ({"faq_id": "F-{n}", "question": "How do I delete my account and all my data?",
              "faq_answer": "You can deactivate your workspace from Settings; deactivation hides the workspace but retains data for ninety days."},
             {"answered": False, "action": "partial"}),
            ({"faq_id": "F-{n}", "question": "Which countries do you ship to?",
              "faq_answer": "We currently ship to all EU countries, the UK, the US and Canada. Other regions are planned for next year."},
             {"answered": True, "action": "answer"}),
            ({"faq_id": "F-{n}", "question": "Can you integrate with our SAP ERP?",
              "faq_answer": "We offer a public REST API and prebuilt connectors for Slack, Zapier and Salesforce."},
             {"answered": False, "action": "partial"}),
            ({"faq_id": "F-{n}", "question": "How long do refunds take to appear?",
              "faq_answer": "Approved refunds are processed within two business days and typically appear on your statement within five."},
             {"answered": True, "action": "answer"}),
        ],
    },
    # -----------------------------------------------------------------------
    # Commerce
    # -----------------------------------------------------------------------
    {
        "key": "catalog_qa", "name": "Marketplace listing QA", "industry": "Commerce",
        "monogram": "CQ", "pattern": "listing guardrail", "prefix": "CAT",
        "blurb": "Screen seller listings before publish: misleading-claim and missing-spec gates "
                 "drive a publish/edit/reject route across millions of catalog entries.",
        "header": "Product listing submitted by a marketplace seller",
        "primary": "description", "fields": [("title", "Title"), ("price", "Price"),
                                              ("category", "Category")],
        "questions": {
            "misleading": {"type": "boolean",
                           "instructions": "Does the listing contain misleading claims?",
                           "criteria": {
                               "true": "The listing contains misleading claims such as impossible performance, fake certifications, medical cures or bait pricing.",
                               "false": "The listing makes only ordinary, plausible product claims."}},
            "missing_specs": {"type": "boolean",
                              "instructions": "Are essential specs missing?",
                              "criteria": {
                                  "true": "Essential specifications such as dimensions, materials, capacity or compatibility are missing from the listing.",
                                  "false": "The listing includes the essential specifications a buyer needs."}},
            "action": {"type": "choice", "instructions": "Catalog action.",
                       "criteria": {
                           "publish": "The listing should be published because its claims are ordinary and its specs are complete.",
                           "edit": "The listing should be sent back for edits because specs are missing but claims are fine.",
                           "reject": "The listing should be rejected because it makes misleading claims."}},
        },
        "truth_map": {"misleading": "misleading", "missing_specs": "missing_specs",
                      "action": "action"},
        "pool": [
            ({"title": "{product}", "price": "EUR 59", "category": "home",
              "description": "Stainless steel body, 1.5 L capacity, 220-240 V, 3-year warranty. Dimensions 24 x 16 x 16 cm, weight 1.2 kg."},
             {"misleading": False, "missing_specs": False, "action": "publish"}),
            ({"title": "MIRACLE CURE Bracelet", "price": "EUR 199", "category": "wellness",
              "description": "Clinically proven to cure arthritis, diabetes and insomnia within 7 days. Doctors hate it. 100% guaranteed or your money back forever."},
             {"misleading": True, "missing_specs": True, "action": "reject"}),
            ({"title": "Wireless earbuds", "price": "EUR 39", "category": "electronics",
              "description": "Great sound, nice design. Battery lasts long. Ships fast."},
             {"misleading": False, "missing_specs": True, "action": "edit"}),
            ({"title": "{product}", "price": "EUR 1 (real price 89)", "category": "home",
              "description": "LOWEST PRICE ON THE INTERNET — listed at 1 euro, final price adjusted at checkout. Limited to first 1000 buyers per hour."},
             {"misleading": True, "missing_specs": False, "action": "reject"}),
            ({"title": "Kids rain jacket", "price": "EUR 34", "category": "apparel",
              "description": "Waterproof rating 5000 mm, sizes 98-140, materials: recycled polyester shell, taped seams, reflective strips, machine washable at 30C."},
             {"misleading": False, "missing_specs": False, "action": "publish"}),
            ({"title": "Phone charger 200W", "price": "EUR 12", "category": "electronics",
              "description": "Charges ANY phone to 100% in 5 minutes, military-grade, certified by NASA. No returns needed because it never breaks."},
             {"misleading": True, "missing_specs": True, "action": "reject"}),
            ({"title": "Yoga mat", "price": "EUR 25", "category": "sports",
              "description": "Non-slip surface in four colors. Very comfortable and popular with our customers."},
             {"misleading": False, "missing_specs": True, "action": "edit"}),
            ({"title": "Espresso machine", "price": "EUR 249", "category": "home",
              "description": "15-bar pump, 1.8 L tank, stainless steel boiler, compatible with ESE pods, 2-year EU warranty, dimensions 33 x 28 x 38 cm."},
             {"misleading": False, "missing_specs": False, "action": "publish"}),
            ({"title": "Slimming tea — lose 10 kg in a week", "price": "EUR 29", "category": "food",
              "description": "Detox formula endorsed by celebrities. Guaranteed 10 kg weight loss in 7 days without diet or exercise."},
             {"misleading": True, "missing_specs": True, "action": "reject"}),
            ({"title": "USB-C hub", "price": "EUR 45", "category": "electronics",
              "description": "7-in-1 hub: HDMI 4K@60, 2x USB-A 3.0, SD/microSD, 100 W PD. Works with macOS and Windows laptops. Aluminum body, cable length 15 cm."},
             {"misleading": False, "missing_specs": False, "action": "publish"}),
        ],
    },
    {
        "key": "price_anomaly", "name": "Price-change anomaly gate", "industry": "Commerce",
        "monogram": "PZ", "pattern": "fat-finger detection", "prefix": "PRZ",
        "blurb": "Catch decimal-shift disasters before they reach the storefront: is this price "
                 "change a mistake or a planned promotion? Apply / hold / reject in seconds.",
        "header": "Price change event from the catalog system",
        "primary": "note", "fields": [("sku", "SKU"), ("old_price", "Old"), ("new_price", "New"),
                                       ("changed_by", "By")],
        "questions": {
            "likely_error": {"type": "boolean",
                             "instructions": "Does the change look like a mistake?",
                             "criteria": {
                                 "true": "This price change looks like a mistake such as a fat-finger entry, a decimal shift or a currency mix-up.",
                                 "false": "This price change looks intentional, such as a planned promotion, seasonal adjustment or cost pass-through."}},
            "action": {"type": "choice", "instructions": "System action.",
                       "criteria": {
                           "apply": "The system should apply the price change because it is intentional.",
                           "hold": "The system should hold the price change for review because its intent is unclear.",
                           "reject": "The system should reject the price change because it is an obvious mistake."}},
        },
        "truth_map": {"likely_error": "likely_error", "action": "action"},
        "pool": [
            ({"sku": "SKU-{n}", "old_price": 89.0, "new_price": 8.9, "changed_by": "intern_{n}",
              "note": "Bulk edit via spreadsheet import; no promotion scheduled for this SKU."},
             {"likely_error": True, "action": "reject"}),
            ({"sku": "SKU-{n}", "old_price": 49.0, "new_price": 39.0, "changed_by": "pricing_bot",
              "note": "Planned Black Friday promotion, approved in campaign CMP-{n}, margin floor respected."},
             {"likely_error": False, "action": "apply"}),
            ({"sku": "SKU-{n}", "old_price": 120.0, "new_price": 12000.0, "changed_by": "vendor_feed",
              "note": "Automated vendor feed update; magnitude jump x100 with no matching cost change."},
             {"likely_error": True, "action": "reject"}),
            ({"sku": "SKU-{n}", "old_price": 25.0, "new_price": 27.5, "changed_by": "pricing_bot",
              "note": "Supplier cost increased 8%; standard pass-through per policy PR-{n}."},
             {"likely_error": False, "action": "apply"}),
            ({"sku": "SKU-{n}", "old_price": 199.0, "new_price": 19.9, "changed_by": "manual",
              "note": "Manual single-SKU edit late at night, outside campaign calendar."},
             {"likely_error": True, "action": "hold"}),
            ({"sku": "SKU-{n}", "old_price": 15.0, "new_price": 13.5, "changed_by": "pricing_bot",
              "note": "Competitor-matched price within the agreed -10% band."},
             {"likely_error": False, "action": "apply"}),
            ({"sku": "SKU-{n}", "old_price": 5.0, "new_price": 500.0, "changed_by": "manual",
              "note": "Price update after catalog cleanup; unclear whether units or cents were intended."},
             {"likely_error": True, "action": "hold"}),
            ({"sku": "SKU-{n}", "old_price": 79.0, "new_price": 79.0, "changed_by": "pricing_bot",
              "note": "No-op refresh triggered by the nightly feed reconciliation."},
             {"likely_error": False, "action": "apply"}),
            ({"sku": "SKU-{n}", "old_price": 640.0, "new_price": 64.0, "changed_by": "intern_{n}",
              "note": "Student temp adjusted 'a few prices' before the weekend; no approval ticket."},
             {"likely_error": True, "action": "reject"}),
            ({"sku": "SKU-{n}", "old_price": 32.0, "new_price": 29.0, "changed_by": "category_mgr",
              "note": "End-of-season markdown for the garden category, ticket MKT-{n} approved."},
             {"likely_error": False, "action": "apply"}),
        ],
    },
    {
        "key": "fake_review", "name": "Fake-review detection", "industry": "Commerce",
        "monogram": "FK", "pattern": "authenticity screening", "prefix": "FKR",
        "blurb": "Screen reviews for paid-praise and competitor-hit patterns using text plus "
                 "account signals — trust-safety teams only see the held queue.",
        "header": "Product review flagged for authenticity screening",
        "primary": "text", "fields": [("reviewer", "Reviewer"), ("account_age_days", "Acct age"),
                                       ("verified_purchase", "Verified")],
        "questions": {
            "likely_fake": {"type": "boolean",
                            "instructions": "Does the review look fake?",
                            "criteria": {
                                "true": "This review looks fake: generic superlatives without product detail, competitor bashing, a fresh single-purpose account, or an unverified extreme rating.",
                                "false": "This review looks genuine: it mentions specific product details in balanced, experience-based wording."}},
            "verdict": {"type": "choice", "instructions": "Screening verdict.",
                        "criteria": {
                            "publish": "The screen should publish this review because it looks genuine.",
                            "hold": "The screen should hold this review for manual check because its authenticity is unclear.",
                            "remove": "The screen should remove this review because it looks fake."}},
        },
        "truth_map": {"likely_fake": "likely_fake", "verdict": "verdict"},
        "pool": [
            ({"reviewer": "user{n}", "account_age_days": 3, "verified_purchase": False,
              "text": "BEST PRODUCT EVER!!! Five stars, buy it now, better than all the other brands which are garbage. Amazing amazing amazing!"},
             {"likely_fake": True, "verdict": "remove"}),
            ({"reviewer": "{name}", "account_age_days": 800, "verified_purchase": True,
              "text": "Used the {product} daily for three months. The battery really lasts a full week; the strap could be softer though. Solid value at this price."},
             {"likely_fake": False, "verdict": "publish"}),
            ({"reviewer": "shopfan{n}", "account_age_days": 1, "verified_purchase": False,
              "text": "Don't buy from this store, their {product} broke instantly. The competitor {company} is way better and cheaper. 1 star."},
             {"likely_fake": True, "verdict": "remove"}),
            ({"reviewer": "{name}", "account_age_days": 1200, "verified_purchase": True,
              "text": "Delivery took two days longer than promised, but the {product} itself works exactly as described. Four stars."},
             {"likely_fake": False, "verdict": "publish"}),
            ({"reviewer": "happy{n}buyer", "account_age_days": 5, "verified_purchase": False,
              "text": "Incredible quality, fast shipping, perfect seller! 10/10 would buy again. No negatives whatsoever."},
             {"likely_fake": True, "verdict": "hold"}),
            ({"reviewer": "{name}", "account_age_days": 400, "verified_purchase": True,
              "text": "It's okay. Does the job but the instructions are confusing and the app is clunky. Might return it if the clunkiness persists."},
             {"likely_fake": False, "verdict": "publish"}),
            ({"reviewer": "deals4you{n}", "account_age_days": 2, "verified_purchase": False,
              "text": "I was paid to write honest reviews and this one is amazing. Everyone should order ten units immediately before the price goes up."},
             {"likely_fake": True, "verdict": "remove"}),
            ({"reviewer": "{name}", "account_age_days": 2000, "verified_purchase": True,
              "text": "Second {product} from this brand. The hinge improved over the 2024 model; customer service replaced a worn cable without fuss."},
             {"likely_fake": False, "verdict": "publish"}),
            ({"reviewer": "newuser{n}", "account_age_days": 7, "verified_purchase": False,
              "text": "Super duper fantastic!!! My whole family loves it, all our friends ordered one too after seeing mine. Perfect in every way!!"},
             {"likely_fake": True, "verdict": "hold"}),
            ({"reviewer": "{name}", "account_age_days": 600, "verified_purchase": True,
              "text": "Works well for the price. The 'waterproof' claim survived a rainy commute, but the case scratches easily — keep that in mind."},
             {"likely_fake": False, "verdict": "publish"}),
        ],
    },
    {
        "key": "returns_triage", "name": "Returns desk triage", "industry": "Commerce",
        "monogram": "RT", "pattern": "policy gating", "prefix": "RET",
        "blurb": "Route return requests against policy: auto-approve the clean ones, inspect the "
                 "borderline, deny the violators — the returns desk without the reading.",
        "header": "Return request with the customer's stated reason",
        "primary": "reason_text", "fields": [("order_age_days", "Age"), ("item", "Item"),
                                             ("amount", "Amount")],
        "questions": {
            "policy_violation": {"type": "boolean",
                                 "instructions": "Does the request violate the return policy?",
                                 "criteria": {
                                     "true": "The request violates the return policy: it is past the 30-day window, the goods are used or damaged by the customer, or the category is excluded.",
                                     "false": "The request is within the return policy: inside the window with an eligible reason."}},
            "route": {"type": "choice", "instructions": "Returns-desk route.",
                      "criteria": {
                          "auto_approve": "The desk should auto-approve the return because it is clearly within policy.",
                          "inspect": "The desk should approve the return with inspection because the item's condition needs checking.",
                          "deny": "The desk should deny the return because it violates the policy."}},
        },
        "truth_map": {"policy_violation": "policy_violation", "route": "route"},
        "pool": [
            ({"order_age_days": 4, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "Arrived yesterday but it's the wrong size. Unopened, all tags on. Would like a refund."},
             {"policy_violation": False, "route": "auto_approve"}),
            ({"order_age_days": 95, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "I know it's been three months but I only just noticed the color isn't what I expected. Can I still send it back?"},
             {"policy_violation": True, "route": "deny"}),
            ({"order_age_days": 12, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "The screen flickers after a week of use. Box and accessories all present."},
             {"policy_violation": False, "route": "inspect"}),
            ({"order_age_days": 20, "item": "underwear 3-pack", "amount": "EUR {amount}",
              "reason_text": "Didn't fit, opened the packaging and tried one on. Want to return all three."},
             {"policy_violation": True, "route": "deny"}),
            ({"order_age_days": 2, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "Ordered two by accident, one is still sealed in the box."},
             {"policy_violation": False, "route": "auto_approve"}),
            ({"order_age_days": 28, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "Works fine but I found it cheaper elsewhere. Sealed, receipt attached."},
             {"policy_violation": False, "route": "auto_approve"}),
            ({"order_age_days": 40, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "The handle snapped while carrying normal weight — I think it's a defect. Photos attached."},
             {"policy_violation": False, "route": "inspect"}),
            ({"order_age_days": 60, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "Changed my mind about the purchase. Item has been used daily for two months but looks fine."},
             {"policy_violation": True, "route": "deny"}),
            ({"order_age_days": 6, "item": "{product}", "amount": "EUR {amount}",
              "reason_text": "Package was visibly crushed on arrival; the lamp inside has a cracked base."},
             {"policy_violation": False, "route": "inspect"}),
            ({"order_age_days": 9, "item": "gift card 50 EUR", "amount": "EUR 50",
              "reason_text": "Bought the gift card by mistake, it is unused, code not redeemed."},
             {"policy_violation": True, "route": "deny"}),
        ],
    },
    {
        "key": "entity_match", "name": "Catalog entity matching", "industry": "Commerce",
        "monogram": "EM", "pattern": "entity alignment (cookbook)", "prefix": "ENT",
        "blurb": "The knowledge-graph entity-alignment cookbook at catalog scale: do two listings "
                 "from different feeds describe the same product? Merge, review or keep apart.",
        "header": "Two catalog listings that may describe the same product",
        "primary": "listing_a", "label_primary": "Listing A",
        "footer_fields": ["listing_b"], "fields": [("source_a", "Src A"), ("source_b", "Src B")],
        "questions": {
            "same_product": {"type": "boolean",
                             "instructions": "Do the listings describe the same product?",
                             "criteria": {
                                 "true": "Listing A and Listing B describe the same product, allowing for different wording, units or packaging descriptions.",
                                 "false": "Listing A and Listing B describe different products, models or variants."}},
            "action": {"type": "choice", "instructions": "Linker action.",
                       "criteria": {
                           "merge": "The linker should merge the two listings because they are the same product.",
                           "review": "The linker should send the pair to human review because the match is uncertain.",
                           "keep": "The linker should keep the listings separate because they are different products."}},
        },
        "truth_map": {"same_product": "same_product", "action": "action"},
        "pool": [
            ({"source_a": "feed-1", "source_b": "feed-2",
              "listing_a": "Acme Wireless Earbuds Pro, black, charging case included, 6h battery",
              "listing_b": "Acme EarBuds Pro (Black) — wireless bluetooth earphones with case, 6 hours playtime"},
             {"same_product": True, "action": "merge"}),
            ({"source_a": "feed-1", "source_b": "feed-3",
              "listing_a": "Acme Wireless Earbuds Pro, black",
              "listing_b": "Acme Wireless Earbuds Lite, white, compact fit"},
             {"same_product": False, "action": "keep"}),
            ({"source_a": "feed-2", "source_b": "feed-3",
              "listing_a": "NordSteel Chef Knife 20cm, forged, walnut handle",
              "listing_b": "Nord Steel professional chef's knife 200 mm forged with walnut grip"},
             {"same_product": True, "action": "merge"}),
            ({"source_a": "feed-1", "source_b": "feed-2",
              "listing_a": "Luna Yoga Mat 6mm, purple, TPE material",
              "listing_b": "Luna Yoga Mat 4mm travel size, purple"},
             {"same_product": False, "action": "keep"}),
            ({"source_a": "feed-3", "source_b": "feed-4",
              "listing_a": "BrewMaster 5000 espresso machine, stainless, 15 bar",
              "listing_b": "BrewMaster 5000 — 15-bar pump espresso maker (stainless steel)"},
             {"same_product": True, "action": "merge"}),
            ({"source_a": "feed-2", "source_b": "feed-4",
              "listing_a": "TrailMaster 40L backpack, green",
              "listing_b": "TrailMaster 40 liter hiking rucksack, grey/orange"},
             {"same_product": False, "action": "review"}),
            ({"source_a": "feed-1", "source_b": "feed-4",
              "listing_a": "PureTone BT-520 headphones, over-ear, ANC, 40h",
              "listing_b": "Pure Tone BT520 over ear headphones with active noise cancelling — 40 hour battery"},
             {"same_product": True, "action": "merge"}),
            ({"source_a": "feed-3", "source_b": "feed-1",
              "listing_a": "KidsZone building blocks, 240 pieces",
              "listing_b": "KidsZone building blocks bucket, 500 pieces"},
             {"same_product": False, "action": "keep"}),
            ({"source_a": "feed-2", "source_b": "feed-3",
              "listing_a": "VoltFit power bank 20000 mAh, 22.5 W, USB-C",
              "listing_b": "VoltFit 20,000mAh portable charger 22.5W fast charging USB C"},
             {"same_product": True, "action": "merge"}),
            ({"source_a": "feed-4", "source_b": "feed-2",
              "listing_a": "AeroPress coffee maker, standard, with filters",
              "listing_b": "AeroPress Go travel set — includes mug and stirrer"},
             {"same_product": False, "action": "review"}),
        ],
    },
    # -----------------------------------------------------------------------
    # Finance
    # -----------------------------------------------------------------------
    {
        "key": "aml_alert", "name": "AML alert triage", "industry": "FinTech",
        "monogram": "AM", "pattern": "false-positive pruning", "prefix": "AML",
        "blurb": "Most transaction-monitoring alerts are false positives. Prune them with a "
                 "first-pass judgment so investigators only open the ones with real red flags.",
        "header": "Transaction-monitoring alert with context",
        "primary": "alert_text", "fields": [("rule", "Rule"), ("amount", "Amount"),
                                            ("customer_years", "Customer")],
        "questions": {
            "likely_false_positive": {"type": "boolean",
                                      "instructions": "Is the alert likely a false positive?",
                                      "criteria": {
                                          "true": "This alert is likely a false positive: the activity matches the customer's known profile and the rule commonly over-triggers on such behaviour.",
                                          "false": "This alert contains genuine red flags such as structuring, unexplained velocity, or high-risk corridors inconsistent with the profile."}},
            "disposition": {"type": "choice", "instructions": "Analyst disposition.",
                            "criteria": {
                                "close": "The analyst should close the alert because the activity matches the customer profile.",
                                "rfi": "The analyst should request more information because key facts are unverified.",
                                "escalate": "The analyst should escalate to an investigation because red flags remain."}},
        },
        "truth_map": {"likely_false_positive": "likely_false_positive",
                      "disposition": "disposition"},
        "pool": [
            ({"rule": "VELOCITY-3", "amount": "EUR {amount}", "customer_years": 9,
              "alert_text": "Customer with nine-year history and steady payroll profile made three card purchases in one hour totalling EUR 210 at grocery and fuel merchants in their home city."},
             {"likely_false_positive": True, "disposition": "close"}),
            ({"rule": "STRUCT-9", "amount": "EUR 9,400 total", "customer_years": 1,
              "alert_text": "New customer made eleven cash deposits of EUR 850-950 across four branches in two days, each just below the reporting threshold, no stated source of funds."},
             {"likely_false_positive": False, "disposition": "escalate"}),
            ({"rule": "GEO-2", "amount": "EUR {amount}", "customer_years": 5,
              "alert_text": "Transfer to a merchant in a high-risk corridor; customer runs an import business with three years of similar, documented supplier payments."},
             {"likely_false_positive": True, "disposition": "close"}),
            ({"rule": "GEO-7", "amount": "EUR {amount}", "customer_years": 2,
              "alert_text": "Overnight wire to an unrelated shell-company account in a sanctioned-adjacent jurisdiction; customer is a freelance graphic designer with no trade history."},
             {"likely_false_positive": False, "disposition": "escalate"}),
            ({"rule": "ROUND-1", "amount": "EUR 25,000", "customer_years": 3,
              "alert_text": "Single round-amount transfer labelled 'property down payment'; supporting notary document uploaded but beneficiary name differs slightly from the contract."},
             {"likely_false_positive": False, "disposition": "rfi"}),
            ({"rule": "PEER-4", "amount": "EUR {amount}", "customer_years": 12,
              "alert_text": "Monthly standing order to the customer's own savings account at another bank, same amount and date for four years."},
             {"likely_false_positive": True, "disposition": "close"}),
            ({"rule": "CASH-2", "amount": "EUR {amount}", "customer_years": 7,
              "alert_text": "Restaurant owner deposits weekend cash takings every Monday; amounts fluctuate with season exactly like the last three years."},
             {"likely_false_positive": True, "disposition": "close"}),
            ({"rule": "CRYPTO-5", "amount": "EUR {amount}", "customer_years": 1,
              "alert_text": "Rapid in-and-out: funds arrive by wire and leave to three different crypto exchanges within hours, repeated five times this month."},
             {"likely_false_positive": False, "disposition": "escalate"}),
            ({"rule": "AMT-6", "amount": "EUR {amount}", "customer_years": 4,
              "alert_text": "One-off payment double the usual rent amount; memo says 'rent + deposit for new flat', landlord matches the known payee."},
             {"likely_false_positive": True, "disposition": "close"}),
            ({"rule": "STRUCT-9", "amount": "EUR 7,800 total", "customer_years": 2,
              "alert_text": "Eight ATM withdrawals just under the monitoring limit in three cities over one weekend; customer stated they were travelling but no matching card activity."},
             {"likely_false_positive": False, "disposition": "rfi"}),
        ],
    },
    {
        "key": "loan_intake", "name": "Loan intake screening", "industry": "FinTech",
        "monogram": "LO", "pattern": "intake banding", "prefix": "LON",
        "blurb": "First-pass screening of loan applications: documents complete? which review "
                 "band? Auto-approve-ready files skip the queue entirely.",
        "header": "Loan application intake notes",
        "primary": "notes", "fields": [("amount", "Amount"), ("term_months", "Term"),
                                       ("credit_band", "Credit band")],
        "questions": {
            "docs_complete": {"type": "boolean",
                              "instructions": "Are all required documents present?",
                              "criteria": {
                                  "true": "All required documents are present and readable: identity, income proof and bank statements.",
                                  "false": "One or more required documents are missing, unreadable or expired."}},
            "band": {"type": "choice", "instructions": "Review band.",
                     "criteria": {
                         "auto": "The application belongs in the auto-approve band because everything is clean and documented.",
                         "standard": "The application belongs in the standard review band because one point needs a human look.",
                         "high_risk": "The application belongs in the high-risk band because multiple risk factors combine."}},
        },
        "truth_map": {"docs_complete": "docs_complete", "band": "band"},
        "pool": [
            ({"amount": "EUR 8,000", "term_months": 24, "credit_band": "A",
              "notes": "Salaried applicant, 6 years at the same employer. Payslips x3, ID and 3 months of bank statements all attached and legible. No open defaults."},
             {"docs_complete": True, "band": "auto"}),
            ({"amount": "EUR 45,000", "term_months": 60, "credit_band": "C",
              "notes": "Self-employed applicant; only one year of accounts provided where three are required. Credit band C with one missed payment last year."},
             {"docs_complete": False, "band": "high_risk"}),
            ({"amount": "EUR 15,000", "term_months": 36, "credit_band": "B",
              "notes": "All documents attached but the income certificate is from 2023; needs a fresh one before decisioning."},
             {"docs_complete": False, "band": "standard"}),
            ({"amount": "EUR 5,000", "term_months": 12, "credit_band": "A",
              "notes": "Repeat borrower, previous two loans repaid early. Full documentation on file from the last application, updated payslip attached."},
             {"docs_complete": True, "band": "auto"}),
            ({"amount": "EUR 120,000", "term_months": 84, "credit_band": "C",
              "notes": "Large unsecured request, three recent credit inquiries, income proof shows high variable commission with no base salary."},
             {"docs_complete": True, "band": "high_risk"}),
            ({"amount": "EUR 22,000", "term_months": 48, "credit_band": "B",
              "notes": "ID, payslips and statements attached; debt-to-income ratio sits at the band boundary, needs manual look."},
             {"docs_complete": True, "band": "standard"}),
            ({"amount": "EUR 3,000", "term_months": 12, "credit_band": "A",
              "notes": "Application submitted but the bank statements PDF is corrupt and cannot be opened."},
             {"docs_complete": False, "band": "standard"}),
            ({"amount": "EUR 60,000", "term_months": 72, "credit_band": "D",
              "notes": "Band D applicant, active collection account, and the requested amount is eight times the declared monthly income."},
             {"docs_complete": True, "band": "high_risk"}),
            ({"amount": "EUR 12,000", "term_months": 36, "credit_band": "B",
              "notes": "Documents complete; applicant changed employers two months ago so income continuity needs a quick manual check."},
             {"docs_complete": True, "band": "standard"}),
            ({"amount": "EUR 2,500", "term_months": 6, "credit_band": "A",
              "notes": "Existing customer with payroll direct-debit to us; all checks automated and green, docs complete."},
             {"docs_complete": True, "band": "auto"}),
        ],
    },
    {
        "key": "expense_audit", "name": "Expense report audit", "industry": "Finance",
        "monogram": "EX", "pattern": "policy compliance gate", "prefix": "EXP",
        "blurb": "Line-item expense auditing at scale: policy-violation detection and an "
                 "approve/justify/reject route — finance only opens the flagged queue.",
        "header": "Expense report line with receipt OCR text",
        "primary": "receipt_text", "fields": [("category", "Category"), ("amount", "Amount"),
                                              ("policy_cap", "Cap")],
        "questions": {
            "policy_violation": {"type": "boolean",
                                 "instructions": "Does the expense violate policy?",
                                 "criteria": {
                                     "true": "This expense violates the policy: it exceeds the category cap, is alcohol-only, lacks a receipt, or is clearly personal spending.",
                                     "false": "This expense complies with the policy: within the cap, business-related and properly receipted."}},
            "action": {"type": "choice", "instructions": "Auditor action.",
                       "criteria": {
                           "approve": "The auditor should approve the expense because it complies with the policy.",
                           "justify": "The auditor should ask for justification because the expense is borderline.",
                           "reject": "The auditor should reject the expense because it violates the policy."}},
        },
        "truth_map": {"policy_violation": "policy_violation", "action": "action"},
        "pool": [
            ({"category": "meals", "amount": "EUR 42", "policy_cap": "EUR 60",
              "receipt_text": "Restaurant receipt, Tuesday 12:31, two business lunches, itemized food and water, card ending 4417, client name written on the slip."},
             {"policy_violation": False, "action": "approve"}),
            ({"category": "meals", "amount": "EUR 180", "policy_cap": "EUR 60",
              "receipt_text": "Steakhouse receipt for four people including three bottles of wine, total 180 EUR, no client names noted."},
             {"policy_violation": True, "action": "reject"}),
            ({"category": "transport", "amount": "EUR 65", "policy_cap": "EUR 120",
              "receipt_text": "Taxi receipt from the airport to the client site, dated during the recorded customer visit, itemized fare."},
             {"policy_violation": False, "action": "approve"}),
            ({"category": "transport", "amount": "EUR 95", "policy_cap": "EUR 120",
              "receipt_text": "Ride receipt at 23:40 from a bar district to a residential address in the employee's home city; no business context."},
             {"policy_violation": True, "action": "justify"}),
            ({"category": "hotels", "amount": "EUR 210", "policy_cap": "EUR 180",
              "receipt_text": "Hotel folio for two nights, room rate above the city cap, minibar charges included."},
             {"policy_violation": True, "action": "justify"}),
            ({"category": "software", "amount": "EUR 29", "policy_cap": "EUR 200",
              "receipt_text": "Monthly subscription invoice for the team's diagramming tool, billed to the company card."},
             {"policy_violation": False, "action": "approve"}),
            ({"category": "meals", "amount": "EUR 55", "policy_cap": "EUR 60",
              "receipt_text": "No receipt attached; employee notes 'cash lunch with contractor, receipt lost'."},
             {"policy_violation": True, "action": "reject"}),
            ({"category": "transport", "amount": "EUR 38", "policy_cap": "EUR 120",
              "receipt_text": "Train ticket invoice, same-day return to the regional office, seat reservation included."},
             {"policy_violation": False, "action": "approve"}),
            ({"category": "entertainment", "amount": "EUR 340", "policy_cap": "EUR 150",
              "receipt_text": "Concert tickets, four seats, submitted under client entertainment; no client attendance documented."},
             {"policy_violation": True, "action": "reject"}),
            ({"category": "office", "amount": "EUR 84", "policy_cap": "EUR 300",
              "receipt_text": "Ergonomic keyboard and mouse for the home office, approved under the remote-work equipment policy."},
             {"policy_violation": False, "action": "approve"}),
        ],
    },
    {
        "key": "dispute_triage", "name": "Chargeback dispute triage", "industry": "FinTech",
        "monogram": "DT", "pattern": "liability pre-judgment", "prefix": "DSP",
        "blurb": "Pre-judge chargeback packages: is the merchant likely liable, and should the "
                 "desk fight, accept, or gather evidence first? Compelling-evidence triage at volume.",
        "header": "Chargeback dispute package summary",
        "primary": "summary", "fields": [("amount", "Amount"), ("reason_code", "Code"),
                                         ("evidence", "Evidence")],
        "questions": {
            "merchant_liable": {"type": "boolean",
                                "instructions": "Is the merchant likely liable?",
                                "criteria": {
                                    "true": "The merchant is likely liable: delivery proof is missing, the wrong item shipped, or the billing was erroneous.",
                                    "false": "The merchant likely fulfilled the order correctly, with signed delivery proof and matching records."}},
            "route": {"type": "choice", "instructions": "Dispute-desk route.",
                      "criteria": {
                          "accept": "The desk should accept the chargeback because the merchant is liable.",
                          "fight": "The desk should fight the chargeback because the evidence favors the merchant.",
                          "gather": "The desk should seek more evidence first because liability is unclear."}},
        },
        "truth_map": {"merchant_liable": "merchant_liable", "route": "route"},
        "pool": [
            ({"amount": "EUR {amount}", "reason_code": "13.1 merchandise not received",
              "evidence": "signed delivery + GPS",
              "summary": "Customer claims non-delivery, but the carrier record shows a signed delivery to the billing address with a timestamped photo, and the IP at purchase matches the account's city."},
             {"merchant_liable": False, "route": "fight"}),
            ({"amount": "EUR {amount}", "reason_code": "13.3 not as described",
              "evidence": "none",
              "summary": "Customer received the blue model after ordering black; warehouse pick-list confirms the wrong variant was shipped and the return is already in transit."},
             {"merchant_liable": True, "route": "accept"}),
            ({"amount": "EUR {amount}", "reason_code": "10.4 other fraud — card absent",
              "evidence": "AVS match",
              "summary": "True-fraud claim, but AVS and CVV both matched, device fingerprint equals the customer's 3-year history device, and delivery went to the verified address. Partial evidence only."},
             {"merchant_liable": False, "route": "gather"}),
            ({"amount": "EUR {amount}", "reason_code": "13.7 cancelled merchandise",
              "evidence": "email thread",
              "summary": "Customer emailed a cancellation within the free-cancel window; support agent acknowledged it, yet the order shipped anyway due to a warehouse race."},
             {"merchant_liable": True, "route": "accept"}),
            ({"amount": "EUR {amount}", "reason_code": "13.1 merchandise not received",
              "evidence": "none",
              "summary": "No tracking number was ever uploaded for this order; the carrier cannot confirm delivery and the fulfilment log has a gap for that day."},
             {"merchant_liable": True, "route": "accept"}),
            ({"amount": "EUR {amount}", "reason_code": "12.6 duplicate processing",
              "evidence": "refund receipt",
              "summary": "Customer was indeed charged twice by a gateway retry; the duplicate was already refunded before the dispute was filed — refund receipt attached."},
             {"merchant_liable": False, "route": "fight"}),
            ({"amount": "EUR {amount}", "reason_code": "13.3 not as described",
              "evidence": "product page snapshot",
              "summary": "Buyer claims the jacket is not waterproof; the product page snapshot clearly states 'water-resistant' and the care label matches. Buyer remorse is likely, but wording is close."},
             {"merchant_liable": False, "route": "gather"}),
            ({"amount": "EUR {amount}", "reason_code": "10.4 other fraud — card absent",
              "evidence": "none",
              "summary": "First-time buyer, shipping to a freight forwarder, different billing country, no 3DS enrollment — classic friendly-fraud or stolen-card pattern with no counter-evidence."},
             {"merchant_liable": True, "route": "accept"}),
            ({"amount": "EUR {amount}", "reason_code": "13.1 merchandise not received",
              "evidence": "signed delivery",
              "summary": "Signed delivery to the stated address two days before the dispute; however the signature name is illegible and the customer says a neighbour accepted it."},
             {"merchant_liable": False, "route": "gather"}),
            ({"amount": "EUR {amount}", "reason_code": "13.8 merchandise not received — digital",
              "evidence": "download logs",
              "summary": "Digital goods claim; server logs show three successful downloads from the buyer's account and email, and the license key was activated."},
             {"merchant_liable": False, "route": "fight"}),
        ],
    },
]
