"""Spec-driven use-case packs (4/4): HR, media, ads/marketing/sales, manufacturing & logistics."""
from __future__ import annotations

PACKS_D: list[dict] = [
    # -----------------------------------------------------------------------
    # HR
    # -----------------------------------------------------------------------
    {
        "key": "job_post_bias", "name": "Job-ad bias screening", "industry": "HR tech",
        "monogram": "JB", "pattern": "inclusive-language gate", "prefix": "JPB",
        "blurb": "Screen every job ad before publishing: biased-wording detection and a "
                 "publish/edit/rewrite route — inclusive hiring at requisition volume.",
        "header": "Draft job advertisement",
        "primary": "text", "fields": [("role", "Role"), ("team", "Team")],
        "questions": {
            "biased_language": {"type": "boolean",
                                "instructions": "Does the ad contain biased wording?",
                                "criteria": {
                                    "true": "The ad contains biased wording such as gendered pronouns, age cues like 'young' or 'fresh', or culture-fit euphemisms that discourage protected groups.",
                                    "false": "The ad uses neutral, requirements-focused wording that welcomes all qualified applicants."}},
            "action": {"type": "choice", "instructions": "Publishing action.",
                       "criteria": {
                           "publish": "The ad is ready to publish because its wording is neutral.",
                           "edit": "The ad needs minor wording edits because isolated phrases are biased.",
                           "rewrite": "The ad needs a rewrite because biased wording pervades it."}},
        },
        "truth_map": {"biased_language": "biased_language", "action": "action"},
        "pool": [
            ({"role": "Backend Engineer", "team": "Payments",
              "text": "We are looking for a backend engineer with 4+ years of Python experience to join our payments team. Hybrid work, parental leave for all parents, accessibility accommodations available."},
             {"biased_language": False, "action": "publish"}),
            ({"role": "Sales Development Rep", "team": "GTM",
              "text": "Wanted: young, hungry, aggressive closer to dominate our market. He must thrive in a work-hard-play-hard brotherhood atmosphere. No part-timers."},
             {"biased_language": True, "action": "rewrite"}),
            ({"role": "Office Manager", "team": "People Ops",
              "text": "Seeking a highly organized office manager. The ideal candidate is a digital native, fresh out of college, who fits our fun youthful vibe."},
             {"biased_language": True, "action": "edit"}),
            ({"role": "Data Analyst", "team": "Insights",
              "text": "Data analyst wanted: SQL, dashboards, curiosity. We review applications anonymously and value diverse career paths including bootcamps and self-taught backgrounds."},
             {"biased_language": False, "action": "publish"}),
            ({"role": "Nurse Practitioner", "team": "Clinic",
              "text": "Our clinic seeks a nurse practitioner. She will handle patient intake and chronic-care follow-ups, working alongside our male-dominated surgical staff."},
             {"biased_language": True, "action": "edit"}),
            ({"role": "Senior Designer", "team": "Product",
              "text": "Senior product designer, 6+ years, portfolio required. Flexible hours, four-day week pilot, and we cover childcare costs during on-site weeks."},
             {"biased_language": False, "action": "publish"}),
            ({"role": "Warehouse Lead", "team": "Ops",
              "text": "Strong male warehouse lead needed for physical work; must be able to lift 40 kg. Veterans and career changers especially encouraged to apply."},
             {"biased_language": True, "action": "edit"}),
            ({"role": "Marketing Manager", "team": "Brand",
              "text": "Marketing manager to own lifecycle campaigns. Requirements: 5 years B2B marketing, analytics fluency. We adjust interview formats on request and post salary bands."},
             {"biased_language": False, "action": "publish"}),
            ({"role": "Junior Dev", "team": "Platform",
              "text": "Rockstar ninja coder wanted for our bro-grammer team! If you can't hack 60-hour sprints and beer Fridays, don't bother applying."},
             {"biased_language": True, "action": "rewrite"}),
            ({"role": "Accountant", "team": "Finance",
              "text": "Staff accountant (part-time options available): reconciliation, VAT filings, audit prep. Quiet, focused environment; remote-first with quarterly meetups."},
             {"biased_language": False, "action": "publish"}),
        ],
    },
    {
        "key": "exit_interview", "name": "Exit interview coding", "industry": "HR tech",
        "monogram": "XI", "pattern": "retention analytics", "prefix": "EXI",
        "blurb": "Code every exit interview for regrettable-loss status and primary theme so "
                 "retention analytics run on all exits, not the ten the CHRO reads personally.",
        "header": "Exit interview notes",
        "primary": "notes", "fields": [("role", "Role"), ("tenure_years", "Tenure"),
                                       ("destination", "Destination")],
        "questions": {
            "regrettable_loss": {"type": "boolean",
                                 "instructions": "Is this a regrettable loss?",
                                 "criteria": {
                                     "true": "This is a regrettable loss: a strong performer leaving for growth, compensation or management reasons the company could have addressed.",
                                     "false": "This departure is not regrettable: performance issues, relocation, retirement, or a personal choice unrelated to the company."}},
            "theme": {"type": "choice", "instructions": "Primary departure theme.",
                      "criteria": {
                          "compensation": "The main theme of the departure is compensation.",
                          "growth": "The main theme of the departure is career growth.",
                          "management": "The main theme of the departure is management or culture.",
                          "personal": "The main theme of the departure is personal or relocation."}},
        },
        "truth_map": {"regrettable_loss": "regrettable_loss", "theme": "theme"},
        "pool": [
            ({"role": "Senior Engineer", "tenure_years": 4, "destination": "competitor",
              "notes": "Top performer, promoted once. Leaving because the competitor's offer is 40% higher and our equity refresh was denied twice. Explicitly said she'd stay for a fair band."},
             {"regrettable_loss": True, "theme": "compensation"}),
            ({"role": "Product Designer", "tenure_years": 3, "destination": "scale-up",
              "notes": "Strong ratings every cycle. Frustrated that design had no career ladder and every promotion went to engineering; wants a lead track we couldn't offer yet."},
             {"regrettable_loss": True, "theme": "growth"}),
            ({"role": "Support Agent", "tenure_years": 1, "destination": "career change",
              "notes": "On a performance-improvement plan since month seven. Leaving to retrain as a electrician; wishes the team well, no complaints about pay."},
             {"regrettable_loss": False, "theme": "personal"}),
            ({"role": "Sales Director", "tenure_years": 6, "destination": "competitor",
              "notes": "Exceeded quota four years running. Says his skip-level micromanages every deal and blocked two of his hires; the final straw was the re-org without consultation."},
             {"regrettable_loss": True, "theme": "management"}),
            ({"role": "Accountant", "tenure_years": 8, "destination": "retirement",
              "notes": "Retiring on schedule at 66 with a full pension. Long, appreciated tenure; leaving entirely for personal reasons."},
             {"regrettable_loss": False, "theme": "personal"}),
            ({"role": "Data Scientist", "tenure_years": 2, "destination": "FAANG",
              "notes": "Solid contributor. Got an offer with a much higher base and research time we can't match; said the work itself was fulfilling."},
             {"regrettable_loss": True, "theme": "compensation"}),
            ({"role": "Marketing Manager", "tenure_years": 3, "destination": "relocation",
              "notes": "Partner transferred to {city}; family relocating. Rated the company highly in every survey and asked to stay in touch for a possible remote return."},
             {"regrettable_loss": False, "theme": "personal"}),
            ({"role": "DevOps Engineer", "tenure_years": 2, "destination": "startup",
              "notes": "Good performer. Left because the manager took credit for his on-call rewrite and denied his conference budget while approving others'."},
             {"regrettable_loss": True, "theme": "management"}),
            ({"role": "Junior Analyst", "tenure_years": 1, "destination": "graduate school",
              "notes": "Leaving for a planned master's program; performance was average but attitude great. Always intended to study after a year of work."},
             {"regrettable_loss": False, "theme": "growth"}),
            ({"role": "Engineering Manager", "tenure_years": 5, "destination": "competitor",
              "notes": "Grew the team from 4 to 14 with zero regretted attrition until now. Says there is no path to director here and the compensation band froze three years."},
             {"regrettable_loss": True, "theme": "growth"}),
        ],
    },
    {
        "key": "engagement_pulse", "name": "Pulse-survey comment coding", "industry": "HR tech",
        "monogram": "EG", "pattern": "verbatim coding at scale", "prefix": "EGP",
        "blurb": "Code thousands of anonymous pulse comments for disengagement and theme so HR "
                 "acts on the signal, not the squeakiest comment.",
        "header": "Anonymous pulse-survey comment",
        "primary": "comment", "fields": [("department", "Dept"), ("tenure", "Tenure")],
        "questions": {
            "disengaged": {"type": "boolean",
                           "instructions": "Does the comment show disengagement?",
                           "criteria": {
                               "true": "The comment shows disengagement: cynicism, burnout signals, quiet-quitting language or intent to leave.",
                               "false": "The comment shows engagement or neutral, constructive feedback without burnout or exit signals."}},
            "theme": {"type": "choice", "instructions": "Primary theme of the comment.",
                      "criteria": {
                          "workload": "The comment is about workload and burnout.",
                          "recognition": "The comment is about recognition and reward.",
                          "management": "The comment is about management.",
                          "tools": "The comment is about tools and processes.",
                          "positive": "The comment is positive or neutral overall."}},
        },
        "truth_map": {"disengaged": "disengaged", "theme": "theme"},
        "pool": [
            ({"department": "Engineering", "tenure": "3y",
              "comment": "I've been carrying two teams' on-call since March. I'm completely burnt out and honestly just going through the motions until I find something else."},
             {"disengaged": True, "theme": "workload"}),
            ({"department": "Sales", "tenure": "1y",
              "comment": "Hit 130% of quota two quarters straight and haven't heard a single thank-you, while others got spot bonuses for less. Starting to wonder why I push."},
             {"disengaged": True, "theme": "recognition"}),
            ({"department": "Support", "tenure": "4y",
              "comment": "Great teammates and I like the customers, but decisions from leadership keep flip-flopping on the ticketing migration. It wastes everyone's weeks."},
             {"disengaged": False, "theme": "tools"}),
            ({"department": "Marketing", "tenure": "2y",
              "comment": "My manager actually shields the team from noise and fights for our training budget. Best part of working here."},
             {"disengaged": False, "theme": "positive"}),
            ({"department": "Engineering", "tenure": "6y",
              "comment": "Third re-org in two years, each one announced over Slack with no context. I've stopped believing anything leadership says and I'm quietly interviewing."},
             {"disengaged": True, "theme": "management"}),
            ({"department": "Finance", "tenure": "5y",
              "comment": "The new expense tool cut processing time in half. Minor gripe: the mobile app still can't scan receipts."},
             {"disengaged": False, "theme": "tools"}),
            ({"department": "Support", "tenure": "2y",
              "comment": "Proud of our CSAT this quarter. Would love the company to share customer thank-you notes more widely — they mean a lot on hard days."},
             {"disengaged": False, "theme": "recognition"}),
            ({"department": "Sales", "tenure": "8m",
              "comment": "Expected ramp support for three months, got a login and a quota. Sink or swim culture — half my onboarding cohort already left."},
             {"disengaged": True, "theme": "management"}),
            ({"department": "Engineering", "tenure": "4y",
              "comment": "Work-life balance is genuinely good here and the codebase is healthy. I'd stay forever if the promotion criteria were transparent."},
             {"disengaged": False, "theme": "recognition"}),
            ({"department": "Operations", "tenure": "1y",
              "comment": "Doing the work of three people since the layoffs, with frozen headcount and 'just prioritize' as the only answer. Can't keep this up much longer."},
             {"disengaged": True, "theme": "workload"}),
        ],
    },
    # -----------------------------------------------------------------------
    # Media
    # -----------------------------------------------------------------------
    {
        "key": "headline_quality", "name": "Headline quality gate", "industry": "Media",
        "monogram": "HQ", "pattern": "editorial QA", "prefix": "HDL",
        "blurb": "Gate headlines against their own article: clickbait detection plus a "
                 "publish/edit/rewrite verdict — editorial standards enforced at CMS speed.",
        "header": "Proposed headline with the article's first paragraph",
        "primary": "headline", "label_primary": "Headline",
        "footer_fields": ["lede"], "fields": [("section", "Section")],
        "questions": {
            "clickbait": {"type": "boolean",
                          "instructions": "Is the headline clickbait?",
                          "criteria": {
                              "true": "The headline is clickbait: it teases, exaggerates or withholds the substance that the article actually delivers.",
                              "false": "The headline accurately summarizes the substance of the article."}},
            "quality": {"type": "choice", "instructions": "Editorial verdict.",
                        "criteria": {
                            "publish": "The headline is publish-ready because it is accurate and informative.",
                            "edit": "The headline needs an edit because it is partially misleading.",
                            "rewrite": "The headline needs a rewrite because it is pure clickbait."}},
        },
        "truth_map": {"clickbait": "clickbait", "quality": "quality"},
        "pool": [
            ({"section": "business",
              "headline": "Central bank holds rates at 3.5%, signals patience on cuts",
              "lede": "The central bank kept its benchmark rate unchanged at 3.5% on Thursday and said it would wait for two more months of cooling inflation data before considering cuts."},
             {"clickbait": False, "quality": "publish"}),
            ({"section": "business",
              "headline": "You WON'T BELIEVE what the central bank just did to your savings",
              "lede": "The central bank kept its benchmark rate unchanged at 3.5% on Thursday and said it would wait for two more months of cooling inflation data."},
             {"clickbait": True, "quality": "rewrite"}),
            ({"section": "tech",
              "headline": "City approves 40 km of protected bike lanes over three years",
              "lede": "The city council voted 31-9 on Tuesday to build 40 kilometers of protected cycling lanes over three years, funded from the municipal transport budget."},
             {"clickbait": False, "quality": "publish"}),
            ({"section": "tech",
              "headline": "This one weird infrastructure trick is destroying car culture",
              "lede": "The city council voted 31-9 to build 40 kilometers of protected cycling lanes over three years, funded from the municipal transport budget."},
             {"clickbait": True, "quality": "rewrite"}),
            ({"section": "science",
              "headline": "Researchers link deep-sea vent bacteria to new enzyme family",
              "lede": "A team sampling hydrothermal vents in the Atlantic identified bacteria whose enzymes remain stable above 120C, a property useful for industrial catalysis."},
             {"clickbait": False, "quality": "publish"}),
            ({"section": "health",
              "headline": "Doctors are stunned by this miracle morning habit",
              "lede": "A small observational study of 40 participants found that drinking water before breakfast correlated with slightly reported energy levels; authors caution against firm conclusions."},
             {"clickbait": True, "quality": "rewrite"}),
            ({"section": "sports",
              "headline": "United stun City 3-2 with 94th-minute winner in derby thriller",
              "lede": "United scored twice in stoppage time to beat City 3-2 in the derby, with the winner coming in the 94th minute from a corner scramble."},
             {"clickbait": False, "quality": "publish"}),
            ({"section": "business",
              "headline": "Retailer's profits fell — here's the shocking reason CEOs are panicking",
              "lede": "The retailer reported a 4% decline in quarterly profit, which it attributed to higher logistics costs and softer demand in its clothing division."},
             {"clickbait": True, "quality": "edit"}),
            ({"section": "culture",
              "headline": "National museum returns 22 bronze artifacts to country of origin",
              "lede": "The national museum announced it will return 22 bronze artifacts taken during a colonial expedition in 1897, following a two-year agreement process."},
             {"clickbait": False, "quality": "publish"}),
            ({"section": "tech",
              "headline": "Startup raises $40M Series B to expand grid-battery software",
              "lede": "The two-year-old startup closed a $40M Series B led by a climate fund to scale its battery-orchestration software across European utility pilots."},
             {"clickbait": False, "quality": "publish"}),
        ],
    },
    {
        "key": "translation_qa", "name": "Translation QA (meaning drift)", "industry": "Media",
        "monogram": "TQ", "pattern": "cross-lingual entailment", "prefix": "TRQ",
        "blurb": "Does the translation still mean what the source says? Entailment between "
                 "source and target catches dropped negations, invented numbers and tone shifts.",
        "header": "Translation quality check",
        "primary": "source_text", "label_primary": "Source (English)",
        "footer_fields": ["translated_text"], "fields": [("target_lang", "Target")],
        "questions": {
            "meaning_preserved": {"type": "boolean",
                                  "instructions": "Does the translation preserve the meaning?",
                                  "criteria": {
                                      "true": "The translation conveys the same meaning as the source text, allowing for natural phrasing differences.",
                                      "false": "The translation changes, drops, adds or reverses meaning compared to the source text."}},
            "action": {"type": "choice", "instructions": "QA action.",
                       "criteria": {
                           "accept": "The translation should be accepted because it preserves the meaning.",
                           "edit": "The translation should be lightly edited because the meaning survives with rough phrasing.",
                           "retranslate": "The translation should be retranslated because it changes the meaning."}},
        },
        "truth_map": {"meaning_preserved": "meaning_preserved", "action": "action"},
        "pool": [
            ({"target_lang": "German",
              "source_text": "The warranty does not cover water damage.",
              "translated_text": "Die Garantie deckt keine Wasserschäden ab."},
             {"meaning_preserved": True, "action": "accept"}),
            ({"target_lang": "German",
              "source_text": "The warranty does not cover water damage.",
              "translated_text": "Die Garantie deckt Wasserschäden ab."},
             {"meaning_preserved": False, "action": "retranslate"}),
            ({"target_lang": "French",
              "source_text": "Press the button for three seconds until the light blinks.",
              "translated_text": "Appuyez sur le bouton pendant trois secondes jusqu'à ce que le voyant clignote."},
             {"meaning_preserved": True, "action": "accept"}),
            ({"target_lang": "French",
              "source_text": "Press the button for three seconds until the light blinks.",
              "translated_text": "Appuyez sur le bouton pendant trente secondes jusqu'à ce que le voyant clignote."},
             {"meaning_preserved": False, "action": "retranslate"}),
            ({"target_lang": "Spanish",
              "source_text": "Store in a cool, dry place away from sunlight.",
              "translated_text": "Conservar en un lugar fresco y seco, lejos de la luz solar."},
             {"meaning_preserved": True, "action": "accept"}),
            ({"target_lang": "Spanish",
              "source_text": "Do not operate the device while charging.",
              "translated_text": "Puede operar el dispositivo mientras se carga."},
             {"meaning_preserved": False, "action": "retranslate"}),
            ({"target_lang": "German",
              "source_text": "Children under 3 should use the toy only under supervision.",
              "translated_text": "Kinder unter 3 Jahren sollten das Spielzeug nur unter Aufsicht verwenden."},
             {"meaning_preserved": True, "action": "accept"}),
            ({"target_lang": "French",
              "source_text": "The subscription renews automatically unless cancelled 24 hours before.",
              "translated_text": "L'abonnement se renouvelle automatiquement, sauf annulation au moins 24 heures avant."},
             {"meaning_preserved": True, "action": "accept"}),
            ({"target_lang": "Spanish",
              "source_text": "Maximum load: 5 kg per shelf.",
              "translated_text": "Carga máxima: 50 kg por estante."},
             {"meaning_preserved": False, "action": "retranslate"}),
            ({"target_lang": "German",
              "source_text": "This medicine may cause drowsiness; avoid driving after taking it.",
              "translated_text": "Dieses Medikament kann müde machen; fahren Sie nach der Einnahme möglichst kein Auto."},
             {"meaning_preserved": True, "action": "edit"}),
        ],
    },
    {
        "key": "duplicate_content", "name": "CMS duplicate detection", "industry": "Media",
        "monogram": "DP", "pattern": "entailment dedup", "prefix": "DPC",
        "blurb": "Catch rewrites and re-submissions before they hit the CMS: is excerpt B just "
                 "excerpt A in other words? Publish, merge or reject.",
        "header": "Two article excerpts submitted to the CMS",
        "primary": "excerpt_a", "label_primary": "Excerpt A",
        "footer_fields": ["excerpt_b"], "fields": [("author_a", "Author A"), ("author_b", "Author B")],
        "questions": {
            "duplicate": {"type": "boolean",
                          "instructions": "Is excerpt B a duplicate of excerpt A?",
                          "criteria": {
                              "true": "Excerpt B restates the same content as Excerpt A, even with different wording or ordering.",
                              "false": "Excerpt B covers different content from Excerpt A."}},
            "action": {"type": "choice", "instructions": "CMS action for excerpt B.",
                       "criteria": {
                           "publish_both": "The CMS should publish both excerpts because they cover different content.",
                           "merge": "The CMS should merge the excerpts because they overlap heavily but each adds detail.",
                           "reject_second": "The CMS should reject the second excerpt because it merely restates the first."}},
        },
        "truth_map": {"duplicate": "duplicate", "action": "action"},
        "pool": [
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "The festival sold out in four hours this year, with 80,000 tickets gone by midday. Organizers credited the new shuttle system for reducing last year's queues.",
              "excerpt_b": "All 80,000 festival tickets were snapped up within four hours — by noon nothing was left. The organizers say the new shuttle service fixed the queue chaos of the previous year."},
             {"duplicate": True, "action": "reject_second"}),
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "The festival sold out in four hours this year, with 80,000 tickets gone by midday.",
              "excerpt_b": "Separately, the festival's food-market lineup was announced, featuring forty local vendors and two Michelin-starred pop-ups."},
             {"duplicate": False, "action": "publish_both"}),
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "City council approved the riverfront park redesign with a budget of 12 million euros. Construction begins in spring.",
              "excerpt_b": "A 12M EUR budget for redesigning the riverfront park received council approval; work is set to start in the spring."},
             {"duplicate": True, "action": "reject_second"}),
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "The startup's battery software is now used by three national grid operators.",
              "excerpt_b": "The same startup also announced a partnership with a charging-network operator to co-develop vehicle-to-grid features."},
             {"duplicate": False, "action": "publish_both"}),
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "Heavy rain caused flooding in the old town on Tuesday, closing two bridges and forcing evacuations of 200 homes.",
              "excerpt_b": "On Tuesday, torrential rain flooded parts of the old town. Two bridges were shut and around two hundred households had to be evacuated."},
             {"duplicate": True, "action": "merge"}),
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "The museum's new wing opens Friday with a retrospective of postwar photography.",
              "excerpt_b": "Ticket prices for the museum's permanent collection will rise by two euros starting next month, the museum said."},
             {"duplicate": False, "action": "publish_both"}),
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "Unemployment fell to 4.1% in June, the lowest reading since 2019, driven by hiring in logistics and healthcare.",
              "excerpt_b": "June's jobless rate dropped to 4.1 percent — the lowest since 2019 — as logistics and healthcare sectors added staff."},
             {"duplicate": True, "action": "merge"}),
            ({"author_a": "{name}", "author_b": "{name}",
              "excerpt_a": "The regional train line will run on a reduced schedule during the October track works.",
              "excerpt_b": "Bus replacement services for the reduced October train schedule will depart every fifteen minutes from the main station."},
             {"duplicate": False, "action": "publish_both"}),
        ],
    },
    # -----------------------------------------------------------------------
    # Ads / marketing / sales
    # -----------------------------------------------------------------------
    {
        "key": "sponsor_safety", "name": "Ad sponsor safety", "industry": "Advertising",
        "monogram": "SB", "pattern": "brand-safety gate", "prefix": "SPS",
        "blurb": "Decide in milliseconds whether an article is a safe neighbour for a brand's "
                 "ad slot — the pre-bid brand-safety filter that runs on every impression.",
        "header": "Article summary next to a proposed ad placement",
        "primary": "summary", "fields": [("brand", "Brand"), ("section", "Section")],
        "questions": {
            "brand_safe": {"type": "boolean",
                           "instructions": "Is the article brand-safe?",
                           "criteria": {
                               "true": "The article is brand-safe: it contains no violence, tragedy, scandal, hate or divisive political conflict next to the ad slot.",
                               "false": "The article is brand-unsafe: it covers tragedy, conflict, scandal, hate speech or divisive content next to the ad slot."}},
            "category": {"type": "choice", "instructions": "Sponsorship tier.",
                         "criteria": {
                           "premium": "The article fits a premium sponsorship tier because it is positive lifestyle or expert content.",
                           "standard": "The article fits a standard sponsorship tier because it is routine news or business content.",
                           "none": "The article should carry no sponsorship because it covers tragedy, conflict or scandal."}},
        },
        "truth_map": {"brand_safe": "brand_safe", "category": "category"},
        "pool": [
            ({"brand": "{company}", "section": "lifestyle",
              "summary": "Ten easy weeknight pasta recipes using five pantry ingredients or less, with step-by-step photos."},
             {"brand_safe": True, "category": "premium"}),
            ({"brand": "{company}", "section": "news",
              "summary": "Death toll from the highway collision rises to nine as investigators examine the trucking company's maintenance records."},
             {"brand_safe": False, "category": "none"}),
            ({"brand": "{company}", "section": "tech",
              "summary": "Review: the new mid-range phone delivers flagship-level battery life at half the price, with a clean software experience."},
             {"brand_safe": True, "category": "premium"}),
            ({"brand": "{company}", "section": "politics",
              "summary": "Parliament debates the contested immigration bill amid protests; the opposition calls the proposal 'a disgrace' as talks collapse."},
             {"brand_safe": False, "category": "none"}),
            ({"brand": "{company}", "section": "business",
              "summary": "Quarterly earnings roundup: three of five major retailers beat forecasts, helped by logistics cost cuts and private-label growth."},
             {"brand_safe": True, "category": "standard"}),
            ({"brand": "{company}", "section": "sports",
              "summary": "Match report: the home side clinched the title with a 2-1 win; fans celebrated peacefully despite heavy rain."},
             {"brand_safe": True, "category": "standard"}),
            ({"brand": "{company}", "section": "news",
              "summary": "Celebrity chef's restaurant empire collapses into bankruptcy amid allegations of unpaid suppliers and staff wage theft."},
             {"brand_safe": False, "category": "none"}),
            ({"brand": "{company}", "section": "science",
              "summary": "Astronomers map a surprisingly calm galactic core, revising models of how medium-sized galaxies evolve."},
             {"brand_safe": True, "category": "premium"}),
            ({"brand": "{company}", "section": "health",
              "summary": "Study links ultra-processed food marketing to childhood obesity rates; advocates call for stricter ad rules near schools."},
             {"brand_safe": False, "category": "standard"}),
            ({"brand": "{company}", "section": "travel",
              "summary": "Guide to the new night-train routes connecting five capitals, with sleeper-cabin reviews and booking tips."},
             {"brand_safe": True, "category": "premium"}),
        ],
    },
    {
        "key": "ad_claim_check", "name": "Ad-copy claim compliance", "industry": "Marketing",
        "monogram": "AC", "pattern": "claims guardrail", "prefix": "ADC",
        "blurb": "Screen ad copy before it ships: unsubstantiated-claim detection and a "
                 "compliance-risk grade — legal reviews only the flagged minority.",
        "header": "Advertising copy submitted for compliance review",
        "primary": "copy", "fields": [("product", "Product"), ("medium", "Medium")],
        "questions": {
            "unsubstantiated": {"type": "boolean",
                                "instructions": "Does the copy make unsubstantiated claims?",
                                "criteria": {
                                    "true": "The copy makes unsubstantiated claims such as guaranteed results, medical cures, absolute superlatives without evidence, or fabricated statistics.",
                                    "false": "The copy makes only ordinary, supportable marketing claims."}},
            "risk": {"type": "choice", "instructions": "Compliance risk.",
                     "criteria": {
                         "low": "The compliance risk of this copy is low because its claims are supportable.",
                         "medium": "The compliance risk of this copy is medium because one claim needs evidence on file.",
                         "high": "The compliance risk of this copy is high because claims are impossible, medical or guaranteed."}},
        },
        "truth_map": {"unsubstantiated": "unsubstantiated", "risk": "risk"},
        "pool": [
            ({"product": "{product}", "medium": "social",
              "copy": "The {product} keeps drinks cold for up to 12 hours in our lab tests. Free returns within 30 days."},
             {"unsubstantiated": False, "risk": "low"}),
            ({"product": "HerbalSlim tea", "medium": "display",
              "copy": "Guaranteed to cure diabetes and melt 10 kg in a week — doctors don't want you to know this one trick!"},
             {"unsubstantiated": True, "risk": "high"}),
            ({"product": "{product}", "medium": "email",
              "copy": "Join 40,000 happy customers. Rated 4.6 stars from 3,100 verified reviews. Ships tomorrow if you order before 6pm."},
             {"unsubstantiated": False, "risk": "low"}),
            ({"product": "InvestPro course", "medium": "youtube pre-roll",
              "copy": "My system returns 30% monthly, risk-free, 100% of the time. No experience needed — the banks hate this."},
             {"unsubstantiated": True, "risk": "high"}),
            ({"product": "{product}", "medium": "search",
              "copy": "Award-winning design (Red Dot 2025). Water-resistant to IPX7. Two-year warranty included."},
             {"unsubstantiated": False, "risk": "low"}),
            ({"product": "SkinGlow serum", "medium": "social",
              "copy": "Clinically-inspired formula with niacinamide; in our consumer trial, 78% reported smoother skin after four weeks."},
             {"unsubstantiated": False, "risk": "medium"}),
            ({"product": "TurboCharge battery", "medium": "display",
              "copy": "The world's best battery, period. Lasts forever and can never overheat — NASA-grade technology for your car."},
             {"unsubstantiated": True, "risk": "high"}),
            ({"product": "{product}", "medium": "email",
              "copy": "Our softest towel yet, according to a 200-person panel. OEKO-TEX certified cotton, machine washable at 60C."},
             {"unsubstantiated": False, "risk": "low"}),
            ({"product": "FocusMax supplement", "medium": "social",
              "copy": "Replaces your morning coffee entirely. Studies show users need 40% less sleep with zero side effects."},
             {"unsubstantiated": True, "risk": "high"}),
            ({"product": "{product}", "medium": "search",
              "copy": "Comparative claim: charges 2x faster than our previous model (2023), measured at 20C with the included cable."},
             {"unsubstantiated": False, "risk": "medium"}),
        ],
    },
    {
        "key": "lead_scoring", "name": "Inbound lead qualification", "industry": "Sales",
        "monogram": "LS", "pattern": "pipeline pruning", "prefix": "LDS",
        "blurb": "Qualify inbound forms before a rep spends a minute: is the lead sales-ready, "
                 "and which tier works it? The candidate-pruning pattern applied to pipelines.",
        "header": "Inbound lead form with enrichment notes",
        "primary": "notes", "fields": [("company_size", "Size"), ("role_title", "Title"),
                                        ("budget_hint", "Budget")],
        "questions": {
            "sales_qualified": {"type": "boolean",
                                "instructions": "Is the lead sales-qualified?",
                                "criteria": {
                                    "true": "The lead is sales-qualified: a matching job role, a budget signal and a real need within the target segment.",
                                    "false": "The lead is not qualified: a student, a competitor, no budget, or a need the product does not serve."}},
            "tier": {"type": "choice", "instructions": "Outreach tier.",
                     "criteria": {
                         "a": "The lead belongs in tier A because role, budget and timeline all align.",
                         "b": "The lead belongs in tier B because interest is real but budget or timing is not.",
                         "c": "The lead belongs in tier C because it is a student, a competitor or has no need."}},
        },
        "truth_map": {"sales_qualified": "sales_qualified", "tier": "tier"},
        "pool": [
            ({"company_size": "450", "role_title": "VP Engineering", "budget_hint": "approved for Q3",
              "notes": "Evaluating tools to replace a legacy system; asks for a technical deep-dive and procurement contact. Timeline: this quarter."},
             {"sales_qualified": True, "tier": "a"}),
            ({"company_size": "1", "role_title": "Student", "budget_hint": "none",
              "notes": "Writing a university paper about our API design; asks for free academic access and an interview."},
             {"sales_qualified": False, "tier": "c"}),
            ({"company_size": "80", "role_title": "CTO", "budget_hint": "under 10k/yr",
              "notes": "Small SaaS team outgrowing spreadsheets; wants a demo next week but needs to convince a co-founder first."},
             {"sales_qualified": True, "tier": "b"}),
            ({"company_size": "12000", "role_title": "Competitive intel", "budget_hint": "n/a",
              "notes": "Email domain belongs to a direct competitor; questions mirror our pricing page feature-by-feature with no use case given."},
             {"sales_qualified": False, "tier": "c"}),
            ({"company_size": "300", "role_title": "Head of Ops", "budget_hint": "board review in 6 weeks",
              "notes": "Fleet-tracking RFP includes our category; asked for security questionnaire and references from logistics peers."},
             {"sales_qualified": True, "tier": "a"}),
            ({"company_size": "15", "role_title": "Founder", "budget_hint": "maybe next year",
              "notes": "Interested but pre-revenue; explicitly says no budget until they raise. Wants to stay on the newsletter."},
             {"sales_qualified": False, "tier": "b"}),
            ({"company_size": "2200", "role_title": "Procurement Lead", "budget_hint": "tender live",
              "notes": "Public tender for our exact product category closes in three weeks; requests tender documentation and EU hosting confirmation."},
             {"sales_qualified": True, "tier": "a"}),
            ({"company_size": "60", "role_title": "Marketing Manager", "budget_hint": "unsure",
              "notes": "Downloaded two whitepapers, asked a pricing question, but is 'just researching options' with no decision timeline."},
             {"sales_qualified": False, "tier": "b"}),
        ],
    },
    {
        "key": "influencer_vetting", "name": "Influencer brand-risk vetting", "industry": "Marketing",
        "monogram": "IF", "pattern": "partnership gating", "prefix": "INF",
        "blurb": "Vet creator profiles before contracts: brand-risk detection and a "
                 "sign/guard/pass recommendation across thousands of candidates per campaign.",
        "header": "Influencer profile and recent post samples",
        "primary": "bio_and_posts", "fields": [("handle", "Handle"), ("followers", "Followers"),
                                               ("niche", "Niche")],
        "questions": {
            "brand_risk": {"type": "boolean",
                           "instructions": "Does the profile carry brand risk?",
                           "criteria": {
                               "true": "The profile shows brand risk: past controversies, bought-follower signals, offensive content, or themes that clash with family-friendly brands.",
                               "false": "The profile is brand-safe with consistent, authentic content in its niche."}},
            "action": {"type": "choice", "instructions": "Partnership decision.",
                       "criteria": {
                           "sign": "The brand should sign the influencer because the profile is authentic and safe.",
                           "guard": "The brand should negotiate with content guardrails because the profile shows fixable risks.",
                           "pass": "The brand should pass on the influencer because the profile shows serious risk."}},
        },
        "truth_map": {"brand_risk": "brand_risk", "action": "action"},
        "pool": [
            ({"handle": "@home_cook_{n}", "followers": "180k", "niche": "food",
              "bio_and_posts": "Weekly recipe videos, grocery-budget tips, no sponsorships in the last 90 days. Comment section is friendly; engagement rate 6.2% consistent with follower size."},
             {"brand_risk": False, "action": "sign"}),
            ({"handle": "@edgy_truth_{n}", "followers": "95k", "niche": "commentary",
              "bio_and_posts": "Recent posts mock a disability charity campaign; three brand deals ended early last year after controversies. Engagement spiked only on outrage content."},
             {"brand_risk": True, "action": "pass"}),
            ({"handle": "@fit_{name}", "followers": "410k", "niche": "fitness",
              "bio_and_posts": "Solid training content, but followers jumped 200k in one week last year and likes now come mostly from inactive accounts; also promotes an unlicensed supplement."},
             {"brand_risk": True, "action": "guard"}),
            ({"handle": "@techreview_{n}", "followers": "260k", "niche": "tech",
              "bio_and_posts": "Detailed, disclosed device reviews with measured benchmarks; clear #ad labeling on every sponsored post; no controversies in two years of archives."},
             {"brand_risk": False, "action": "sign"}),
            ({"handle": "@travel_diary_{name}", "followers": "75k", "niche": "travel",
              "bio_and_posts": "Beautiful destination guides, but occasionally posts drunk-beach party content with brand logos visible; audience skews 16-24."},
             {"brand_risk": True, "action": "guard"}),
            ({"handle": "@diy_{n}", "followers": "120k", "niche": "home",
              "bio_and_posts": "Step-by-step renovation tutorials, tools disclosed, replies constructively to criticism. Stable growth over three years, engagement 4.8%."},
             {"brand_risk": False, "action": "sign"}),
            ({"handle": "@crypto_moon_{n}", "followers": "300k", "niche": "finance",
              "bio_and_posts": "Promotes unregistered token giveaways, deleted two posts after rug-pull accusations; comments full of users claiming losses."},
             {"brand_risk": True, "action": "pass"}),
            ({"handle": "@garden_gal_{name}", "followers": "48k", "niche": "garden",
              "bio_and_posts": "Seasonal planting guides and composting explainers; partners only with sustainable brands; no political or controversial content."},
             {"brand_risk": False, "action": "sign"}),
        ],
    },
    # -----------------------------------------------------------------------
    # Manufacturing / logistics
    # -----------------------------------------------------------------------
    {
        "key": "quality_defect", "name": "QC defect disposition", "industry": "Manufacturing",
        "monogram": "QD", "pattern": "line disposition gating", "prefix": "QCD",
        "blurb": "Turn inspection notes into dispositions: is the defect critical, and should the "
                 "batch pass, rework or scrap? Quality engineers review only the flagged bins.",
        "header": "Quality-control inspection note from the line",
        "primary": "note", "fields": [("line", "Line"), ("batch", "Batch"),
                                       ("units_affected", "Units")],
        "questions": {
            "critical_defect": {"type": "boolean",
                                "instructions": "Is the defect critical?",
                                "criteria": {
                                    "true": "The defect is critical: a safety hazard, a regulatory breach, or a total loss of function.",
                                    "false": "The defect is cosmetic or minor with no safety or functional impact."}},
            "disposition": {"type": "choice", "instructions": "Batch disposition.",
                            "criteria": {
                                "pass": "The batch should pass because defects are absent or within the approved standard.",
                                "rework": "The batch should be reworked because the defects are fixable.",
                                "scrap": "The batch should be scrapped because the defects are unsafe or unfixable."}},
        },
        "truth_map": {"critical_defect": "critical_defect", "disposition": "disposition"},
        "pool": [
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 0,
              "note": "Full sample within tolerance: dimensions, torque and finish all nominal. No defects found in the 40-unit sample."},
             {"critical_defect": False, "disposition": "pass"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 120,
              "note": "Charger housings crack at the hinge after three open-close cycles; exposed live contacts when cracked — shock hazard."},
             {"critical_defect": True, "disposition": "scrap"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 340,
              "note": "Logo print is 2mm off-center on the whole batch; function unaffected, packaging insert slightly hides it."},
             {"critical_defect": False, "disposition": "rework"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 12,
              "note": "Twelve units fail the waterproof test at 1m depth; specification requires IPX7. Affected units quarantined, rest of batch passes."},
             {"critical_defect": True, "disposition": "rework"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 0,
              "note": "Minor paint orange-peel on two units under bright inspection light, within the customer-approved cosmetic standard COS-{n}."},
             {"critical_defect": False, "disposition": "pass"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 900,
              "note": "Label shows wrong voltage rating (110V printed on 230V units); regulatory marking mismatch — cannot ship as-is."},
             {"critical_defect": True, "disposition": "rework"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 5,
              "note": "Five cartons with dented corners from the palletizer; product inside inspected and undamaged."},
             {"critical_defect": False, "disposition": "pass"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 640,
              "note": "Battery cells from the suspect supplier lot show 15% capacity below spec and swelling after fast-charge cycling — fire risk."},
             {"critical_defect": True, "disposition": "scrap"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 45,
              "note": "Screen protector bubbles on 45 units; cosmetic, easily replaced at pack-out without touching the device."},
             {"critical_defect": False, "disposition": "rework"}),
            ({"line": "L{n}", "batch": "B-{n}", "units_affected": 0,
              "note": "Re-inspection after tooling fix: all critical dimensions in tolerance, CPK 1.67. Batch released by QA lead on shift."},
             {"critical_defect": False, "disposition": "pass"}),
        ],
    },
    {
        "key": "shipment_exception", "name": "Shipment exception triage", "industry": "Logistics",
        "monogram": "SE", "pattern": "exception management", "prefix": "SHP",
        "blurb": "Grade every carrier event: does a human need to intervene, and how badly? "
                 "Most scans self-recover; the intervention queue stays short and prioritized.",
        "header": "Carrier event feed entry for a shipment",
        "primary": "event_text", "fields": [("carrier", "Carrier"), ("lane", "Lane"),
                                            ("eta_delta_h", "ETA delta h")],
        "questions": {
            "needs_intervention": {"type": "boolean",
                                   "instructions": "Does the shipment need human intervention?",
                                   "criteria": {
                                       "true": "The shipment needs human intervention: stuck scans, customs holds, damage, or missed cutoffs that will not recover on their own.",
                                       "false": "The event is a normal scan or a minor delay that will recover without intervention."}},
            "severity": {"type": "choice", "instructions": "Exception severity.",
                         "criteria": {
                             "low": "The exception severity is low because the shipment will recover on its own.",
                             "medium": "The exception severity is medium because the delay needs tracking but not action.",
                             "high": "The exception severity is high because goods or deadlines are at real risk."}},
        },
        "truth_map": {"needs_intervention": "needs_intervention", "severity": "severity"},
        "pool": [
            ({"carrier": "FastFreight", "lane": "HAM->FRA", "eta_delta_h": 0,
              "event_text": "Departed facility Hamburg, arrived hub Frankfurt on schedule. Standard line-haul scan, no anomalies."},
             {"needs_intervention": False, "severity": "low"}),
            ({"carrier": "OceanLink", "lane": "SHA->RTM", "eta_delta_h": 96,
              "event_text": "Container held by customs for missing HS-code documentation on 3 of 11 pallets; vessel already departed, docs needed within 48h to avoid return."},
             {"needs_intervention": True, "severity": "high"}),
            ({"carrier": "ParcelPost", "lane": "local", "eta_delta_h": 4,
              "event_text": "Delivery delayed by four hours due to local weather; driver still has the parcel, redelivery scheduled for tomorrow morning."},
             {"needs_intervention": False, "severity": "low"}),
            ({"carrier": "FastFreight", "lane": "BCN->MAD", "eta_delta_h": 24,
              "event_text": "No scan for 36 hours at a transit point that normally processes within 6; tracking shows the shipment stuck while sibling parcels moved on."},
             {"needs_intervention": True, "severity": "medium"}),
            ({"carrier": "AirCargo", "lane": "JFK->LHR", "eta_delta_h": 12,
              "event_text": "Pallet arrived with crushed corner; carrier photos show two cartons with water staining. Consignee must be notified and photos archived for the claim."},
             {"needs_intervention": True, "severity": "high"}),
            ({"carrier": "ParcelPost", "lane": "local", "eta_delta_h": 0,
              "event_text": "Out for delivery, stop 14 of 62. Recipient not home on first attempt; second attempt automated for tomorrow."},
             {"needs_intervention": False, "severity": "low"}),
            ({"carrier": "RailExpress", "lane": "WAW->DUI", "eta_delta_h": 8,
              "event_text": "Missed the 18:00 cutoff by 40 minutes due to a late inbound truck; rebooked on the next daily departure automatically, ETA plus eight hours."},
             {"needs_intervention": False, "severity": "medium"}),
            ({"carrier": "OceanLink", "lane": "SGN->LAX", "eta_delta_h": 120,
              "event_text": "Rolled to the next vessel at the origin port because of overbooking; new ETD five days out. Contract guarantees space on the following sailing — no action possible beyond informing the customer."},
             {"needs_intervention": True, "severity": "medium"}),
            ({"carrier": "FastFreight", "lane": "MXP->ZRH", "eta_delta_h": 2,
              "event_text": "Arrived at destination depot two hours behind plan; final-mile slots still intact, delivery window unchanged."},
             {"needs_intervention": False, "severity": "low"}),
            ({"carrier": "AirCargo", "lane": "DXB->CDG", "eta_delta_h": 48,
              "event_text": "Temperature logger on the pharma pallet excursed above 8C for three hours on the tarmac; consignee QA must approve or reject before delivery proceeds."},
             {"needs_intervention": True, "severity": "high"}),
        ],
    },
]
